### ISSUE TITLE
Zend From File Count Validation

### ISSUE THREAD

**Issue by starkskalle** [Shardj/zf1-future#10]
Hey,

I cannot provide any more information at the moment but the issue seems to be pretty straight forward:

'count(): Parameter must be an array or an object that implements Countable' in file '/vendor/shardj/zf1-future/library/Zend/Validate/File/Count.php' on line '257'

Running on PHP 7.3.

Let me know if you need any more info.

Thanks

**Comment by Shardj** [comment]
Thanks, I thought I got all of these but it seems like I missed this one. I'll get it sorted

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/commit/7b15f33d9fe20e13d59501f14a121a6e514837b6

Tell me if you want a new tag or anything

**Comment by starkskalle** [comment]
Thanks for the quick action! Is there any way to consume this specific commit via composer so I can give it a try?

**Comment by Shardj** [comment]
"require": {
    "mysoftware/thesoftware": "dev-master#3f38376d"
}

That would work, but I'll just go make a new version for you so that as long as you're asking for the latest version with composer you'll get it.

**Comment by Shardj** [comment]
I've created a new commit release-1.14.2 so you should just be able to use that

**Comment by starkskalle** [comment]
I tried it with locally updated source files and the fix works. However I might prefer a bit to change the line 90 to instead. But it does not make any big difference :-)
`protected $_files = [];`

**Comment by starkskalle** [comment]
Sweet, just updating to the new tag release-1.14.2, thx!
