### ISSUE TITLE
Controller Plugin Broker tries throwing Error to Exception Class

### ISSUE THREAD

**Issue by WebTigers** [Shardj/zf1-future#105]
On lines 263, 298, 312, 336, and 358, the Controller Plugin Broker is catching any \Trowable $e (including Errors) and then tries to re-throw as previous to the Zend_Exception class. If the \Throwable is an Error and not an Exception, PHP complains with a Fatal Error:

`Fatal error: Uncaught TypeError: Argument 3 passed to Zend_Exception::__construct() must be an instance of Exception or null, instance of TypeError given, called in /var/www/tiger-vendor/vendor/shardj/zf1-future/library/Zend/Controller/Plugin/Broker.php on line 312 and defined in /var/www/tiger-vendor/vendor/shardj/zf1-future/library/Zend/Exception.php:43`

Not exactly sure of the best way to handle this. I can trap and re-throw the error within the Controller Plugin, but this feels more like an architectural issue with PHP 7's use of Errors and ErrorExceptions now being handled like Exceptions. Everyone's thoughts on the issue are welcome.

**Comment by Shardj** [comment]
Same issue as being discussed here right? https://github.com/Shardj/zf1-future/commit/ee11356ed7c7f82374d8f016149a731bb1478275

**Comment by WebTigers** [comment]
Yes, appears to be the same issue.

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/releases/tag/release-1.18.6 should be fixed now, sorry that didn't get around to making a new release sooner for you
