### ISSUE TITLE
Text Email sending fails with Array to String conversion notice

### ISSUE THREAD

**Issue by colorninja** [Shardj/zf1-future#118]
First of all, thank you so much for supporting PHP7 for this legacy beast! 

Today I came across a problem, where I get the following notice:
```
message: "Array to string conversion"
code: 8
file: "/var/www/html/vendor/shardj/zf1-future/library/Zend/Mime.php"
line: 472
severity: E_NOTICE
```
when I try to send an email without HTML content - just Text and one attachment.

I had a look around the code and on that line it looks like the `str_replace` function is used incorrectly.
```php
    /**
     * Converts a string into quoted printable format.
     *
     * @param  string $str
     * @return string
     */
    private static function _encodeQuotedPrintable($str)
    {
        $str = str_replace(
            ['=', self::$qpKeys],
            ['=3D', self::$qpReplaceValues],
            $str);
        
        return rtrim($str);
    }
```

qpKeys and qpRelaceValues (both arrays) should be spread in order for it to work as expected in future PHP versions.

We could use the spread operator, but since you are aiming min 7.0 support, another means should be used. I will create a PR soon.

**Comment by Shardj** [comment]
Yeah looks like it's just an array merge needed between ['='] and self::$qpKeys and the same for ['=3D'] and self::$qpReplaceValues for params 1 and 2 respectively. I'll wait for your PR

**Comment by arueckauer** [comment]
Running into the same issue. PR LGTM. Anything I can help get this released?

**Comment by Shardj** [comment]
@arueckauer release-1.18.8 has this out
