### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by colorninja** [Shardj/zf1-future#120]
Is PHP 8 support planned for this repository? I am willing to help support it.

The main changes we need to look out for are listed here: https://stitcher.io/blog/new-in-php-8 under "Breaking changes".

**Comment by glensc** [comment]
x-ref:
- https://github.com/zf1s/zf1/issues/31
- https://github.com/zf1s/zf1/pull/32

**Comment by Shardj** [comment]
Yeah it's absolutely planned, I'll reopen this though until it's supported

**Comment by glensc** [comment]
x-ref:
- https://github.com/zf1s/zf1/pull/39

you should read instructions how to backport from the other repos:
- https://github.com/Shardj/zf1-future/issues/96#issuecomment-740559426

**Comment by jeanmodesto** [comment]
some news about php 8 support ?

**Comment by onlime** [comment]
@Shardj Thanks for this great project! Can I donate somewhere to motivate you a bit working on PHP 8 support? :)

**Comment by Shardj** [comment]
Hey @onlime 

Sorry for the lack of motivation on my part, the webapp I work on that uses ZF1 depends on mssql which doesn't yet support PHP 8. So I've not been super motivated to upgrade ZF1 to PHP 8 since I can't do anything with it anyway yet.

As for donations, I don't yet have a way of accepting them. And I'm not sure if I really can accept donations as I work on this repo both in and out of company hours. So it could probably be considered the intellectual property of my employer as much as my own. I'll look into sorting something out there in the future maybe.

**Comment by Shardj** [comment]
Hey @onlime

Sorry for the lack of motivation on my part, the webapp I work on that uses ZF1 depends on mssql which doesn't yet support PHP 8. So I've not been super motivated to upgrade ZF1 to PHP 8 since I can't do anything with it anyway yet.

As for donations, I don't yet have a way of accepting them. I'll look into sorting something out there in the future maybe.

**Comment by WebTigers** [comment]
@Shardj 

FWIW, ZF1 is an MIT license, so not being a lawyer I'm not sure that your employer has any claim to updates to open source code under an MIT license. They received their benefit by paying you and they have benefited by others updating the project as well, including using the updated open source code that was not updated solely by you. By you keeping the code open source, you're helping the community at large.

I have a commercial project that I will be releasing at the end of this month that uses this project and I will gladly donate and even buy ad space here to help support the project! I'll check out the donations button too!  :)

**Comment by Shardj** [comment]
@WebTigers I'm also not a laywer, and I have no idea as to what exactly is okay in relation to what rights I'd have to be paid through this repo, or any rights my employers may have for work done on this repo during company time. So I've avoided the issue completely by having the donation button on my profile, not on the repo. There's strictly no way to directly donate to this repository at all. I've simply added a way to donate to myself as a person.

**Comment by onlime** [comment]
@Shardj let's discuss the licensing/donation thing later (I definitely want to donate something...). Just want to let you know that I am currently working on a small PR which should be ready shortly. I am doing some 3-way-diff of [zf1s/zf1](https://github.com/zf1s/zf1) monorepo (compiled all packages into `library/Zend/`), my own patched zf1 1.12.20, and your `master` branch.

I will not find time to dig deep into it, as it's impossible to review all diffs between shardj/zf1-future and zf1s/zf1 (even after automated PhpStorm refactoring of all traditional into short array syntax and ignoring all whitespace diff). But after some small fixes, my rather large project (which uses at least a third of all ZF1 components) already seems to work 100% on PHP 8.0.2

**Comment by Shardj** [comment]
@onlime awesome stuff, sounds like a huge step towards PHP 8 support for this repo

**Comment by onlime** [comment]
@Shardj here you go, #130 is mainly @Megatherium's work and it's not yet merged into [zf1s/zf1](https://github.com/zf1s/zf1) master. But I have reviewed all changes and they all make sense. Again, my project that uses quite a lot of ZF1 components runs perfectly fine under PHP 8.0.2 and I am going to run this in production as soon as you merge it, so I would quickly notice any problems.

**Comment by Shardj** [comment]
It's out on release-1.19.0 @onlime 

Enjoy!

**Comment by onlime** [comment]
Great, thanks. But please note that I was not able to run unit tests. If you can get them running please do so and let me know of any problems. Please also update `.travis.yml` and get it running under PHP 8.

**Comment by Shardj** [comment]
#131 

Good point

**Comment by onlime** [comment]
Hey @Shardj, just want to let you know that my rather large legacy ZF1 project is now running perfectly fine for 5 days in production on PHP 8.0 without a single issue!

It's a webhosting controlpanel/dashboard for my customers, so it's a rather complex project that uses ~ 30% of all ZF1 components. We're working on the next-gen customer dashboard which is going to be based on Laravel api backend with Vue.js/Nuxt frontend. But until that's ready, it will all still run on zf1-future. I am so glad you were supporting me getting those fixes for PHP 8 released. I have switched my whole dev environment to PHP8-only, which makes my life even a bit happier than it already is.

Please don't close this issue yet until tests run fine and while we still try to keep up with zf1s/zf1#51

**Comment by onlime** [comment]
3.5 months later, still no single issue with PHP 8.0. @Shardj please consider closing this issue. Or are you still planning to update tests to PHP 8 / migrate to Github actions?
