### ISSUE TITLE
Zend_Cache_Frontend_Page

### ISSUE THREAD

**Issue by richardsalvaia** [Shardj/zf1-future#121]
Hello,

Need to test if variable is_array before test it with count. The error:

https://github.com/Shardj/zf1-future/blob/87ccb2477aa853a5d0ca01dd2e7e11ca70fc3158/library/Zend/Cache/Frontend/Page.php#L398

Uncaught Exception: count(): Parameter must be an array or an object that implements Countable in /vendor/shardj/zf1-future/library/Zend/Cache/Frontend/Page.php:3982.

Stack trace:
#0 vendor/shardj/zf1-future/library/Zend/Cache/Frontend/Page.php(398): RS_Error_Handler::handle()
#1 vendor/shardj/zf1-future/library/Zend/Cache/Frontend/Page.php(346): Zend_Cache_Frontend_Page->_makePartialId()
#2 vendor/shardj/zf1-future/library/Zend/Cache/Frontend/Page.php(264): Zend_Cache_Frontend_Page->_makeId()
#3 application/Bootstrap.php(135): Zend_Cache_Frontend_Page->start()

**Comment by ferranbonas** [comment]
The error has been there since 7.2. Fix:
```
if ($var && count($var) > 0) {
            return false;
}
```

**Comment by richardsalvaia** [comment]
Yes, another approach is:

if (is_array($var) && count($var) > 0) {
     return false;
}

**Comment by Shardj** [comment]
Just committed a fix

**Comment by Shardj** [comment]
Release tag with fix: release-1.18.9
