### ISSUE TITLE
PHP 8.x version_compare error

### ISSUE THREAD

**Issue by Thiiil** [Shardj/zf1-future#128]
As described in https://bugs.php.net/bug.php?id=80503 

PHP 8 doesn't support "gte' operator for version_compare() 

I have found this one triggered only in fpm mode which break several things like Zend_Currency
https://github.com/Shardj/zf1-future/blob/c84dedf0e948d9ccaa7a2ac234cc6f6787f05d45/library/Zend/Xml/Security.php#L172

It's an easy fix, I submit this case for memory / info.

hav a nice day.

**Comment by glensc** [comment]
the line you point to is fixed in zf1s project, included in 1.13.4 release:
- https://github.com/zf1s/zf1/pull/26
