### ISSUE TITLE
Zend\Tool\Project\Provider\DbAdapter.php contains reference to deprecated function get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by cfuhrman** [Shardj/zf1-future#129]
Zend\Tool\Project\Provider\DbAdapter.php contains a reference to the deprecated function get_magic_quotes_gpc().   Per https://www.php.net/manual/en/function.get-magic-quotes-gpc.php, this method only returned false anyway and is now deprecated as of PHP 7.4 (See https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.magic-quotes-functions)

Solution:

Remove the following lines around line # 99 (in _configureViaDSN()):

        // parse_str suffers when magic_quotes is enabled
        if (get_magic_quotes_gpc()) {
            array_walk_recursive($dsnVars, [$this, '_cleanMagicQuotesInValues']);
        }

I can come up with a simple PR if necessary.

**Comment by Shardj** [comment]
I'll make a release with the fix in a bit
