### ISSUE TITLE
ini_set(): Use of iconv.internal_encoding is deprecated in /var/www/myapp/library/Zend/Application.php on line 278

### ISSUE THREAD

**Issue by pierre-alain-b** [Shardj/zf1-future#13]
Dear Maintainer,

What a good surprise to find a fork of ZF1 compatible with PHP 7.3.
However, when deploying it in my app, I see the following error:

Deprecated: ini_set(): Use of iconv.internal_encoding is deprecated in /var/www/myapp/library/Zend/Application.php on line 278

May I do something to avoid this?

Thanks
Pierre

**Comment by Shardj** [comment]
Hi Pierre,

In the options parameter you're passing to the constructor (2nd argument) of library/Zend/Appliation.php do you have phpsettings set which contains 'iconv.internal_encoding'? PHP deprecated that setting from PHP 5.6 onwards. You should really move away from using iconv and remove the setting, but if that isn't possible here is a workaround: https://stackoverflow.com/questions/45165864/php-deprecated-iconv-set-encoding-use-of-iconv-internal-encoding-on-stringle

Google also turns up a lot of custom solutions.

**Comment by pierre-alain-b** [comment]
Extremely helpful, thank you.
