### ISSUE TITLE
Documentation Builder Broken

### ISSUE THREAD

**Issue by WebTigers** [Shardj/zf1-future#133]
Running the documentation builder no longer works. Could be an issue with the domains embedded within the script? Not sure.

**Comment by rruchte** [comment]
The good news: I got the documentation to build (English anyway) by making just a couple of tweaks. 

The bad news: It looks like Zend had a fairly customized set of Docbook XLS stylesheets. The default is pretty spartan.

I dug through the old ZF repos looking for the Docbook XLS but couldn't find it, which is a bit dd - they were pretty complete with everything else. Maybe I'm just missing it? I'm also not a Docbook expert, this is my first exposure to it. I'm comfortable with the underlying technology, but not the specifics of Docbook. Maybe there are commonly available customized catalog stylesheet sets (like skins) that could be a good starting point for a resurrected set of docs?

Is there anyone with Docbook experience that can take a look? I'd rather not spend a bunch of my free time tinkering with XSL.

**Comment by WebTigers** [comment]
Is this something you can push up as a PR for us to take a look at? I'm not familiar with DocBook either, or XSL so much, but I'd like to see what the data looks like. Or you can email the zipped up files to beau at webtigers.com

**Comment by rruchte** [comment]
Sure, I sent you a zip of the output. I pushed [a WIP commit](https://github.com/rruchte/zf1-future/commit/aa44a943e49eb5b473e6225ff586efa519d10df7) that shows the changes I had to make to get the build to complete. In addition to these changes, I had to set the XML_CATALOG_FILES environment variable to /usr/local/etc/xml/catalog which is where homebrew installed them for me (xsltproc will use /etc/xml/catalog by default).

**Comment by rruchte** [comment]
OK, all languages building now, see PR #145
