### ISSUE TITLE
PHP Notice:  "Trying to access array offset on value of type int" in Zend/Locale/Format.php

### ISSUE THREAD

**Issue by michaelcaldwell-st** [Shardj/zf1-future#135]
On PHP version 7.4.15
Using shardj/zf1-future version 1.19.0 (latest at this time)

The exact error message is:

PHP Notice:  Trying to access array offset on value of type int in /home/vagrant/<repo name>/vendor/shardj/zf1-future/library/Zend/Locale/Format.php on line 527

The line of code that breaks in shardj/zf1-future/library/Zend/Locale/Format.php is:

`if (!empty($input) && ($input[0] == $symbols['decimal'])) {  `

where $input is an integer.

Any help you can provide is very much appreciated.  If you can repro or have reports of a similar/same issue and decide to fix, please advise, and I'll help if I can.

**Comment by Shardj** [comment]
$input should be a string

**Comment by michaelcaldwell-st** [comment]
@Shardj here's an actual full call stack for the error:

[24-Feb-2021 14:43:19 America/New_York] PHP Notice: Trying to access array offset on value of type int in /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Locale/Format.php on line 527
	PHP Stack trace:
	PHP  1. {main}() /index.php:0
	PHP  2. Zend_Application->run() /home/vagrant/someapp/public/index.php:96
	PHP  3. Zend_Application_Bootstrap_Bootstrap->run() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Application.php:384
	PHP  4. Zend_Controller_Front->dispatch() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/Bootstrap.php:105
	PHP  5. Zend_Controller_Dispatcher_Standard->dispatch() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Controller/Front.php:954
	PHP  6. Zend_Controller_Action->dispatch() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Controller/Dispatcher/Standard.php:308
	PHP  7. OurController->postAction() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Controller/Action.php:516
	PHP  8. Our_Validate_Model->isValid() /home/vagrant/someapp/application/modules/api/controllers/OurController.php:433
	PHP  9. Our_Validate_Model->isValidElements() /home/vagrant/someapp/library/Our/Validate/Model.php:111
	PHP 10. Zend_Form_Element->isValid() /home/vagrant/someapp/library/Our/Validate/Model.php:495
	PHP 11. Our_Validate_Chain->isValid() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Form/Element.php:1448
	PHP 12. Zend_Validate_Float->isValid() /home/vagrant/someapp/library/Our/Validate/Chain.php:26
	PHP 13. Zend_Locale_Format::isFloat() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Validate/Float.php:124
	PHP 14. Zend_Locale_Format::isNumber() /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Locale/Format.php:679
[24-Feb-2021 14:43:19 America/New_York] PHP Notice: Trying to access array offset on value of type int in /home/vagrant/someapp/vendor/shardj/zf1-future/library/Zend/Locale/Format.php

(I've replaced a few folder names just to obfuscate the proprietary info.)

As you can see, our code has a custom validator at Our/Validate/Chain.php which calls back into Zend_Validate_Float->isValid(), which calls the functions inside Zend_Locale_Format, where the error occurs.  Here's the final call from our code into zf1-future:

![image](https://user-images.githubusercontent.com/77579955/109527941-35b00f80-7a82-11eb-9791-fd7ba5ba9454.png)

Thanks for your reply

**Comment by Shardj** [comment]
Looks like whoever wrote Float.php didn't pay much attention to ints. I've committed a fix and I'll make a minor release

**Comment by michaelcaldwell-st** [comment]
Thank you @Shardj

**Comment by coling** [comment]
Thanks for this fix, but Just a follow-up that this is now causing issue for us. Previously an integer value was valid, but now it's invalid, so an API breakage.

The Float validator previous accepted and int value happily as being a subset of floats. Now this change is in place '1' is a valid float but (int)'1' isn't which seems wrong.

Wouldn't a better fix be to either, 1) accept an int, or 2) cast the int to a string and go through the locale validation (although the second option seems redundant.

**Comment by coling** [comment]
FYI, this is a change in PHP7.4: https://wiki.php.net/rfc/notice-for-non-valid-array-container,

I'll write a new pull request shortly with the correct behaviour.
