### ISSUE TITLE
Zend_Filter MCrypt extension not available

### ISSUE THREAD

**Issue by jcerdan** [Shardj/zf1-future#136]
Hi,

don't know if I'm missing something but I have tried this on PHP 7.4 and it does not work.
On starting the server and accessing the website I got this error:
PHP Fatal error:  Uncaught Zend_Filter_Exception: This filter needs the mcrypt extension library/Zend/Filter/Encrypt/Mcrypt.php:78

This is normal as this extension does not exist since PHP 7.2. How is that supposed to run? 

Regards

**Comment by glensc** [comment]
You could install the polyfill:
- https://github.com/phpseclib/mcrypt_compat

**Comment by Shardj** [comment]
It does still exist since PHP 7.2, it's just not installed by default any more. For example: https://pecl.php.net/package/mcrypt
