### ISSUE TITLE
Zend_Filter_Encrypt_Mcrypt , mcrypt is not supported since php 7.2

### ISSUE THREAD

**Issue by aymencis** [Shardj/zf1-future#137]
Fatal error: Uncaught ErrorException: Function mcrypt_list_algorithms() is deprecated
Fatal error: Uncaught ErrorException: Function mcrypt_list_modes() is deprecated
PHP Fatal error:  Uncaught ErrorException: Function mcrypt_module_self_test() is deprecated

**Comment by glensc** [comment]
Try polyfill:
- https://github.com/Shardj/zf1-future/issues/136#issuecomment-786741904

**Comment by glensc** [comment]
@aymencis your bug report lacks any reproducibility, how can the developer reproduce your problem without even describing what are you doing, what's your php version or how you enabled mcrypt extension?

to me seems if you install from pecl, it does not have methods deprecated:
- https://github.com/Shardj/zf1-future/issues/136#issuecomment-787489865

```
$ git clone -b 1.0.3 https://git.php.net/repository/pecl/encryption/mcrypt.git
$ cd mcrypt
$ git grep E_DEPRECATED
mcrypt_filter.c:        php_error_docref(NULL, E_DEPRECATED, "mcrypt and mdecrypt stream filters have been deprecated");
$
```

**Comment by Shardj** [comment]
#136 already addresses this as glensc linked
