### ISSUE TITLE
Error in View/Helper/Placeholder/Registry.php

### ISSUE THREAD

**Issue by kanapes** [Shardj/zf1-future#146]
Hi, there is a issue in line 102 (short if - new donwload version) - Wrong EOF.

Good job, thx so far and keep on

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/blob/master/library/Zend/View/Helper/Placeholder/Registry.php#L102

Are you referring to the change from:

```
        if (isset($this->_items[$key])) {
            return $this->_items[$key];
        }

        $container = $this->createContainer($key);

        return $container;
```

To 

```
        return $this->_items[$key] ?? $this->createContainer($key);
```

What exactly is the error?

**Comment by kanapes** [comment]
*thumb up* got it 
after changing it works. dont know what happened. i think i got an older version of it ...
