### ISSUE TITLE
Zend_View_Helper_HeadScript error where not View

### ISSUE THREAD

**Issue by GK89** [Shardj/zf1-future#147]
Hi, I'm currently getting this error again on PHP7.3 with zf1 1.19.2: "Zend_View_Helper_HeadScript error where not View". There was a ticket for this before: https://github.com/Shardj/zf1-future/issues/110

In library/Zend/View/Helper/HeadScript.php:440 the replacement with $isHTML5 is still missing

https://github.com/Shardj/zf1-future/blob/ce02d94d0bfbaf728fe27227bec67729ca29ead1/library/Zend/View/Helper/HeadScript.php#L418

https://github.com/Shardj/zf1-future/blob/ce02d94d0bfbaf728fe27227bec67729ca29ead1/library/Zend/View/Helper/HeadScript.php#L441

**Comment by Shardj** [comment]
Merged your PR
