### ISSUE TITLE
zf create project  warning PHP7.3 count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by martin-dufka** [Shardj/zf1-future#15]
Hi,

can you see this? 

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .\zf1-future\library\Zend\Tool\Project\Profile\Resource\Container.php on line 386

I think that count() of boolean will never be an array or an object :) 

It would be 
`return (count($this->_subResources) > 0) ? true : false;` 
instead of 
`return (count($this->_subResources > 0)) ? true : false;`

isn't it?

**Comment by Shardj** [comment]
Thanks
