### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by tarik817** [Shardj/zf1-future#154]
Hi there!
Do you have any estimation when the project will have PHP 8 support?
What should be done? What help do you need to make it happen?

**Comment by Shardj** [comment]
It does have PHP 8 support, my team uses PHP 8 with this repo in a very large production project. Of course everyone uses different modules though so there may still be problems around I haven't found yet.

Thanks for making this though, just noticed the readme still says it's not supporting PHP 8 so I'll go and change that. If you find any issues running this repo in PHP 8 please raise an issue.

**Comment by michaelkeusch** [comment]
Hello, I am a little confused. Does release-1.19.5 support PHP 8? In the master, the README.md took over the support of PHP 8 almost 4 months ago. 
Best regards Michael

**Comment by Shardj** [comment]
It should do, I haven't packaged a release in a while though so I should really do that

**Comment by michaelkeusch** [comment]
Thanks to Shardj and to George for your answers.
May I ask one more question.
Up to which PHP version is the release 1.19.5 backward compatible?
Best regards Michael

**Comment by Shardj** [comment]
7.0 I believe
