### ISSUE TITLE
Error using FlashMessenger

### ISSUE THREAD

**Issue by jmmunozcubo** [Shardj/zf1-future#156]
Helo.

I used the FlashMessenger method (helper method) to access a diferents messages

$this->_helper->FlashMessenger()->setNamespace('referer')->addMessage($uri);

And then I used this value in differents functions.

Now when I used this function zend tell me: 

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Zend_Controller_Action_Helper_FlashMessenger::direct(), 0 passed in /var/www/html/library/Zend/Controller/Action/HelperBroker.php on line 328 and at least 1 expected in /var/www/html/library/Zend/Controller/Action/Helper/FlashMessenger.php:309 Stack trace: #0 /var/www/html/library/Zend/Controller/Action/HelperBroker.php(328): Zend_Controller_Action_Helper_FlashMessenger->direct() #1 /var/www/html/application/modules/default/controllers/ErrorController.php(31): Zend_Controller_Action_HelperBroker->__call() #2 /var/www/html/library/Zend/Controller/Action.php(133): Default_ErrorController->init() #3 /var/www/html/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct() #4 /var/www/html/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch() #5 /var/www/html/bootstrap.php(520): Zend_Controller_Front->dispatch() #6 /var/www/html/bootstrap.php(68): Start::_dispatchController() #7 /var/www/html/public/index.php(67): Start::main() #8 /var/www/html/public/index.php(28): appStart() #9 {main} Next Zend_Controller_Exception: Too few arguments to function Zend_Controller_Action_Helper_FlashMessenger::direct(), 0 passed in /var/www/html/library/Zend/Controller/Action/HelperBroker.php on line 328 and at least 1 expected#0 /var/www/html/library/Zend/Controller/Action/HelperBroker.php(328): Zend_Controller_Action_Helper_FlashMessenger->direct() #1 /var/www/html/application/modules/default/controllers/ErrorController.php(31): Zend_Controller_Action_HelperBroker->__call() #2 /var/www/html/library/Zend/Controller/Action.php(133): Default_ErrorController->init() #3 /var/www/html/library/Zend/Controller/Dispatcher/Standard.php(281): Zend_Controller_Action->__construct() #4 /var/www/html/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch() #5 /var/www/html/bootstrap.php(520): Zend_Controller_Front->dispatch() #6 /var/www/html/bootstrap.php(68): Start::_dispatchController() #7 /var/www/html/public/index.php(67): Start::main() #8 /var/www/html/public/index.php(28): appStart() #9 {main} in /var/www/html/library/Zend/Controller/Plugin/Broker.php:335 Stack trace: #0 /var/www/html/library/Zend/Controller/Front.php(965): Zend_Controller_Plugin_Broker->postDispatch() #1 /var/www/html/bootstrap.php(520): Zend_Controller_Front->dispatch() #2 /var/www/html/bootstrap.php(68): Start::_dispatchController() #3 /var/www/html/public/index.php(67): Start::main() #4 /var/www/html/public/index.php(28): appStart() #5 {main} thrown in /var/www/html/library/Zend/Controller/Plugin/Broker.php on line 335

¿any suggestion?

**Comment by rruchte** [comment]
Remove the parentheses after FlashMessenger. It's not a function, it's an instance of [Zend_Controller_Action_Helper_FlashMessenger](https://github.com/Shardj/zf1-future/blob/master/library/Zend/Controller/Action/Helper/FlashMessenger.php).

`$this->_helper->FlashMessenger->setNamespace('referer')->addMessage($uri);`

**Comment by jmmunozcubo** [comment]
Thank's @rruchte, it's works fine withouth parentheses!
