### ISSUE TITLE
library\Zend\Config\Yaml.php : $line instead of $lines

### ISSUE THREAD

**Issue by llnguyen** [Shardj/zf1-future#16]
Hi,

There is a typo when you migrate an "list ... each" to a foreach.

L292 : It should be
`foreach ($lines as $n => $line) {`
instead of
`foreach `($line` as $n => $line) {`

**Comment by Shardj** [comment]
Thank you, I've committed a fix https://github.com/Shardj/zf1-future/commit/75dc2887b17f21ac806da6c8f0a3d8fd9b995366
