### ISSUE TITLE
Invalid PDOStatement PHP Doc

### ISSUE THREAD

**Issue by wes614** [Shardj/zf1-future#164]
Hey guys/gals,

Just querying what I think is causing one of our linters some hassle. I think this @return PHPDoc should be referencing PDOStatement (without the underscore)?

https://github.com/Shardj/zf1-future/blob/02d513087f82de96587a03c81c9c9b962783f6b8/library/Zend/Db/Select.php#L703

**Comment by glensc** [comment]
can you describe the problem, please?
