### ISSUE TITLE
Zend_Locale_Format::isNumber Inconsistencies

### ISSUE THREAD

**Issue by ddxdental** [Shardj/zf1-future#180]
Found an issue with the locale en_IN where Zend_Validate_Int seemingly incorrectly evaluates Ints.

Test:

```
$locales = ['en', 'en_IN'];
$tests = ['100', 100, '1', 1, '5', 5];

foreach ($locales as $locale) {
    echo 'Locale ' . $locale . PHP_EOL;

    $t = new Zend_Validate_Int(new Zend_Locale($locale));

    foreach ($tests as $test) {
        $r = $t->isValid($test);

        echo 'Test ' . var_export($test, 1) . ' = ' . var_export($r, 1) . PHP_EOL;
    }

    echo PHP_EOL;
}
```

Result

```
Locale en
Test '100' = true
Test 100 = true
Test '1' = true
Test 1 = true
Test '5' = true
Test 5 = true

Locale en_IN
Test '100' = true
Test 100 = true
Test '1' = false
Test 1 = true
Test '5' = false
Test 5 = true
```

in Zend_Locale_Format::isNumber, the regex tests vary between these two locals.

en_IN
```
Array
(
    [0] => /^[++]{0,1}[0-9]{1,2}(\,{0,1}[0-9]{2})*[0-9](\.{1}[0-9]{1,}){0,1}$/u
    [1] => /^[--]{0,1}[0-9]{1,2}(\,{0,1}[0-9]{2})*[0-9](\.{1}[0-9]{1,}){0,1}$/u
    [2] => /^[++]{0,1}[0-9]{1,}(\.[0-9]{1,})*[eE][++]{0,1}[0-9]{1,}$/u
    [3] => /^[--]{0,1}[0-9]{1,}(\.[0-9]{1,})*[eE][--]{0,1}[0-9]{1,}$/u
)

```

en
```
Array
(
    [0] => /^[++]{0,1}[0-9]{1,3}(\,{0,1}[0-9]{3})*(\.{1}[0-9]{1,}){0,1}$/u
    [1] => /^[--]{0,1}[0-9]{1,3}(\,{0,1}[0-9]{3})*(\.{1}[0-9]{1,}){0,1}$/u
    [2] => /^[++]{0,1}[0-9]{1,}(\.[0-9]{1,})*[eE][++]{0,1}[0-9]{1,}$/u
    [3] => /^[--]{0,1}[0-9]{1,}(\.[0-9]{1,})*[eE][--]{0,1}[0-9]{1,}$/u
)
```

Not sure why the difference in patterns between locales (must be a reason), but numbers under 10 require a left padding?  

I'm puzzling through ICU locale specification, and am failing to find meaningful information that would either point to a bug, or validate correct behavior.  Anyone pointers?

**Comment by Shardj** [comment]
Hm yeah this is odd, I can't think of any reasons why '1' and '5' would be false here for en_IN

**Comment by develart-projects** [comment]
As this is breaking change,  any idea what is the correct format?
If there isn't any justification, I suggest not to touch it.

**Comment by develart-projects** [comment]
I tried to locate same resource in Laminas 3, but no success. A nobody seems to be interested anymore, closing this one.
Feel free to reopen, if needed.
