### ISSUE TITLE
Broken Zend_Db_Table_Rowset::current function

### ISSUE THREAD

**Issue by mpichot** [Shardj/zf1-future#194]
Hello,

First of all: thank's a lot to maintain ZF-1. Great work! :-)

Am I wrong? I think the return type of `Zend_Db_Table_Rowset::current` function recently added `mixed` is wrong. The function return `Zend_Db_Table_Row_Abstract` or null. `mixed` is union of `string|int|float|bool|null|array|object|callable|resource`. So Php complain when the function return `Zend_Db_Table_Row_Abstract`.

Here's the hash of the commit: ad81d0c2c6b5ee9207627022197b3a952418256b

Malo

**Comment by WebTigers** [comment]
Bug appears to have been introduced ...
<img width="1107" alt="Screen Shot 2022-01-18 at 10 43 23 AM" src="https://user-images.githubusercontent.com/774030/149969972-f557d6ba-e995-4097-bf99-ce2c72c8c037.png">

**Comment by EugenePikalov** [comment]
Which version of PHP do you use?

**Comment by WebTigers** [comment]
This particular app is 7.4.

**Comment by EugenePikalov** [comment]
mixed is available as of PHP 8.0.0.  https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.mixed

**Comment by hc-jworman** [comment]
Will be fixed in https://github.com/Shardj/zf1-future/pull/196

**Comment by Shardj** [comment]
So, I've upped the required PHP version to 8.0, the final version supporting PHP 7.4 would be 1.20.0. However if this is a problem for lots of people and PHP 7 is still required I'll go back and remove the mixed tags. I was getting warnings during my upgrade to 8.1 with no return type set on those functions so mixed was used.

**Comment by Shardj** [comment]
Just to be clear on why I made the change. You need to use the mixed return type to use PHP 8.1 SeekableIterator interface https://github.com/Shardj/zf1-future/blob/ad81d0c2c6b5ee9207627022197b3a952418256b/library/Zend/Db/Table/Rowset/Abstract.php

PHP docs: https://www.php.net/manual/en/class.seekableiterator.php

**Comment by Shardj** [comment]
I could remove the mixed return type and create a copy of the old SeekableIterator interface to use throughout ZF1 instead, thoughts?

**Comment by hc-jworman** [comment]
You can just put a #[\ReturnTypeWillChange] attribute to mask the deprecation till Php 9.0, and prevent any potential BC breaks.

**Comment by jonnott** [comment]
Following on from my comment on commit 833ee782ed2f852ef44fe1a308f634f6cb9827d6, I'm a bit out of my depth with the specific situation on the mixed return type requirement for SeekableIterator in PHP 8.1, but I'm of the opinion that if there's any way to work around this to maintain PHP 7.3|7.4 support, it should be done.

@hc-jworman 's suggestion above looks plausible..?

**Comment by Shardj** [comment]
> 

Okay thanks I'll do just that then hc-jworman

**Comment by Shardj** [comment]
Actually @hc-jworman do you want to just add those attributes to your PR https://github.com/Shardj/zf1-future/pull/196 and I'll merge it. Thanks for being so proactive with this issue

**Comment by Shardj** [comment]
I'll make a release with the fix

**Comment by Shardj** [comment]
Okay, go nuts: release-1.20.2

**Comment by Shardj** [comment]
Would removing version 1.20.1 help?

**Comment by fredericgboutin-yapla** [comment]
I think so.
