### ISSUE TITLE
Zend_Db_Select REGEX_COLUMN_EXPR

### ISSUE THREAD

**Issue by icyz** [Shardj/zf1-future#200]
The regex  **`/^([\w]*\s*\(([^\(\)]|(?1))*\))$/`**
https://github.com/Shardj/zf1-future/blob/8e2a0d2139f57101d610fc9777769c455f21be49/library/Zend/Db/Select.php#L84

 does not work for this case:

```
$query->from(['c' => $this->defineTableName()], [
"CASE WHEN LENGTH(c.company) > 0 THEN c.company ELSE CONCAT_WS(' ', c.surname, c.name) END AS customer"
]);

```
This is the error I get:
`Column not found: 1054 Unknown column 'CASE WHEN LENGTH(c.company) > 0 THEN c.companyELSE CONCAT_WS(' ', c.surname, c.name) END`

and still works with:
```
$query->from(['c' => $this->defineTableName()], [
"DATE_FORMAT(c.xdate, '%d-%m-%Y') AS xdate_it"
]);
```

The problem is in here :
https://github.com/Shardj/zf1-future/blob/8e2a0d2139f57101d610fc9777769c455f21be49/library/Zend/Db/Select.php#L972

the new regex `/^([\w]*\s*\(([^\(\)]|(?1))*\))$/`  returns false
with the old regex `/\(.*\)/` returns true

```
if (preg_match(self::REGEX_COLUMN_EXPR, (string) $col)) {  // <--- this return 0. With the old regex this will return 1
    $col = new Zend_Db_Expr($col);
} elseif (preg_match('/(.+)\.(.+)/', $col, $m)) {
    $currentCorrelationName = $m[1];
    $col = $m[2];
}
```

I hope it could be helpful, I really love this project, thanks <3

**Comment by hc-jworman** [comment]
The regex was change to stop an sql injection, doing your suggested change would make this test fail:
```php
    public function testSqlInjectionInColumn()
    {
        $select = $this->_db->select();
        $select->from(['p' => 'products'], ['MD5(1); drop table products; -- )']);
        $this->assertEquals('SELECT "p"."MD5(1); drop table products; -- )" FROM "products" AS "p"', $select->assemble());
    }
```

I suggest you manually wrap your expression with `\Zend_Db_Expr` instead.

**Comment by hc-jworman** [comment]
On another note, this shows the importance of having a functional test suite and CI.

If you want ZF1 for PHP 5.3 to 8.1, with passing tests and CI, check out https://github.com/hc-jworman/zf1.

**Comment by fballiano** [comment]
In OpenMage we encountered this same issue, the REGEX doesn't match `COUNT(tr.customer_id) + MIN(IF(tp.base_popularity IS NOT NULL, tp.base_popularity, 0))` while it perfectly match something like `COUNT(DISTINCT tr.product_id)`.

**Comment by develart-projects** [comment]
Imo Zend_Db_Expr() is exactly for this case. Has anyone something against if I close this one as wonfix?
