### ISSUE TITLE
PHP 8.0 Upgrade started throwing "There is no active transaction"

### ISSUE THREAD

**Issue by mumtazumair** [Shardj/zf1-future#201]
As other frameworks also reported the same issue: https://github.com/doctrine/migrations/issues/1202

I am facing this issue in Zend as well.

CREATE TABLE IF NOT EXISTS `schema_update` (
  `id_schema_update` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `module` VARCHAR(25) NOT NULL ,
  `file` VARCHAR(255) NOT NULL ,
  `duration` int(10) NOT NULL COMMENT 'Duration in seconds that the migration takes executing',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `statements` TEXT DEFAULT NULL,
  PRIMARY KEY (`id_schema_update`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

Migration failed: 
There is no active transaction
#0 /vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(290): PDO->commit()
#1 /vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(484): Zend_Db_Adapter_Pdo_Abstract->_commit()
#2 /library/Shm/Dao/Transaction.php(119): Zend_Db_Adapter_Abstract->commit()
#3 /application/modules/ext/maintenance/models/SchemaUpdate.php(207): Shm_Dao_Transaction->commit()
#4 /application/modules/ext/maintenance/models/SchemaUpdate.php(107): Maintenance_Model_SchemaUpdate->runMigrations(true)

Any help is much appreciated.

**Comment by hungtrinh** [comment]
Root cause here:
https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.pdo-mysql

Quick & dirty way to back behavior like before php 8.x

You need something like that, patch content of file

Zend/Db/Adapter/Pdo/Abstract.php
```
   /**
     * Commit a transaction.
     */
    protected function _commit()
    {
        $this->_connect();
        if (!$this->_connection->inTransaction()) {
            return;
        }
        $this->_connection->commit();
    }

    /**
     * Roll-back a transaction.
     */
    protected function _rollBack()
    {
        $this->_connect();
        if (!$this->_connection->inTransaction()) {
            return;
        }
        $this->_connection->rollBack();
    }
```

**Comment by grisha2217** [comment]
> Root cause here: https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.pdo-mysql
> 
> Quick & dirty way to back behavior like before php 8.x
> 
> You need something like that, patch content of file
> 
> Zend/Db/Adapter/Pdo/Abstract.php
> 
> ```
>    /**
>      * Commit a transaction.
>      */
>     protected function _commit()
>     {
>         $this->_connect();
>         if (!$this->_connection->inTransaction()) {
>             return;
>         }
>         $this->_connection->commit();
>     }
> 
>     /**
>      * Roll-back a transaction.
>      */
>     protected function _rollBack()
>     {
>         $this->_connect();
>         if (!$this->_connection->inTransaction()) {
>             return;
>         }
>         $this->_connection->rollBack();
>     }
> ```

This is applies only for PDO? What's about mysqli?
After updating to php 8 & zf1 i get "SAVEPOINT DOES NOT EXISTS" sometimes

**Comment by hungtrinh** [comment]
yep, about issue `SAVEPOINT DOES NOT EXISTS` it's same root cause:
https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

**Comment by pdolinaj** [comment]
That's a good fix! Can this be please added to master branch?

**Comment by develart-projects** [comment]
Anyone to create PR on this?

**Comment by hungtrinh** [comment]
> Anyone to create PR on this?

i'm here :D  solution above. i'm thinking about about test case to cover this case, will create PR soon
