### ISSUE TITLE
SMTP doesn't support TLS 1.2

### ISSUE THREAD

**Issue by Craig-CyberNY** [Shardj/zf1-future#202]
https://github.com/Shardj/zf1-future/blob/8e2a0d2139f57101d610fc9777769c455f21be49/library/Zend/Mail/Protocol/Smtp.php#L197

`STREAM_CRYPTO_METHOD_TLS_CLIENT` only includes TLS 1.0 and according to some back and forth 7 years ago this was done on purpose because PHP 5.6.6 broke some stuff when they changed it and it got reverted in 5.6.7
[https://www.php.net/manual/en/function.stream-socket-enable-crypto.php#119122](https://www.php.net/manual/en/function.stream-socket-enable-crypto.php#119122)

ZF1-future should either follow the example and detect if TLS 1.2 is defined and use that, check if PHP > 5.6.7 and use `STREAM_CRYPTO_METHOD_SSLv23_CLIENT` (should be fine since PHP7 is required), or use `STREAM_CRYPTO_METHOD_ANY_CLIENT` (not sure I love that option since you could technically negotiate over a very insecure crypto method).

This is actually a fairly important change because some major mail hosts have dropped support for TLS < 1.2

**Comment by PHPGangsta** [comment]
In my patched version of `Zend_Mail_Protocol_Smtp` in ZendFramework 1 I have this change:

old:
```if (!stream_socket_enable_crypto($this->_socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {```

new:
```if (!stream_socket_enable_crypto($this->_socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT)) {```

With this I can connect to TLS 1.1 and TLS 1.2 servers. 

It could be that this is the same as using `STREAM_CRYPTO_METHOD_SSLv23_CLIENT`:
https://www.php.net/manual/de/function.stream-socket-enable-crypto.php#119122
```
PHP >= 5.6.7
STREAM_CRYPTO_METHOD_SSLv23_CLIENT = STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
STREAM_CRYPTO_METHOD_TLS_CLIENT = STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT
```
