### ISSUE TITLE
Looking for ZF1 full-stack senior developer

### ISSUE THREAD

**Issue by WebTigers** [Shardj/zf1-future#207]
I know this is a wacky place to post a dev needed request. Sue me.  ;-)

A startup I'm currently with needs another senior full-stack PHP7-8 dev with good to deep ZF1 experience, Bootstrap 4, jQuery, Datatables, Select2, Ajax. Basically the full LAMP stack. AWS experience with knowing your way around an EC2 Amazon Linux instance is also a plus. Node.js a plus as well but not necessary. No need for Angular or React. Email me your resume with base rate if interested. 2-3 month gig on 1099 to star that could turn permanent. Beau@WebTigers.com

**Comment by develart-projects** [comment]
@WebTigers if you like to get good ZF1 developer, don't ask for FE capabilities. My 2 cents :)
Anyway closing.
