### ISSUE TITLE
Possible recursive loop 

### ISSUE THREAD

**Issue by florian-popescu-at-csro** [Shardj/zf1-future#208]
Got error 'PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /opt/www/svp/library/Zend/Controller/Action.php on line 586'

**Comment by Shardj** [comment]
I can't see any immediate recursion in there, the getParam calls against Action.php aren't the same as the getParam calls against the request object.

You do seem to have a memory issue but I don't think there's much we can do to help with the information provided. Would you show your code?

**Comment by florian-popescu-at-csro** [comment]
It's just a simple action in a controller:

public function sendtokenAction() 
	{ 
		$this->_helper->viewRenderer->setNoRender();
		$this->_helper->layout()->disableLayout();		
		
		$email=$this->getParam('email', '');				
		
		ASE_Service_Authentication::sendToken($email);
	}

The getParam call causes the memory issue...

**Comment by Shardj** [comment]
Strange, the memory issue you had is on line 586 yet you're calling getParam not _getParam. Are you sure it's reaching your call to `getParam('email', '')` and the issue isn't somewhere before it reaches the controller like in the Dispatcher? Probably worth stepping through with xdebug or at least throwing some logging in there.

I've never had a memory issue with just using getParam in a controller so I can only assume that the code there isn't the problem.

**Comment by florian-popescu-at-csro** [comment]
Ok. Thanks for the feedback. I'll look forward in the project's code. It's inherited so I'm not familiar with every detail of the project. Thank you again.
