### ISSUE TITLE
1.21.0 update breaks php 7.1 compatibility

### ISSUE THREAD

**Issue by justanerd** [Shardj/zf1-future#210]
This Line doesn't work in PHP 7.1:
`protected static ?array $configParserOptions = null;`

https://github.com/Shardj/zf1-future/blob/818e5609fa7acc41a2ea5cdd708144004b6f070b/library/Zend/Application.php#L70

**Comment by Shardj** [comment]
Sorted https://github.com/Shardj/zf1-future/commit/51dd353ba28a3ae59143301c0d50da4849a46986

**Comment by Shardj** [comment]
release-1.21.1 has the fix
