### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by func0der** [Shardj/zf1-future#226]
Hey,

thanks for keeping zf1 alive and kicking.

A `CHANGELOG.md` or at least something more than `version bump` in the release notes would be great.

Even though there is not that much happening feature-wise, it would be nice to know what those new versions contain in changes.

**Comment by fredericgboutin-yapla** [comment]
Since this project seems to often "backport" from zf1s/zf1 repo, you should have a look at https://github.com/zf1s/zf1/blob/master/CHANGELOG.md

**Comment by glensc** [comment]
sync with zf1s/zf1 is not really happening. zf1-future has evolved beyond goals that zf1s/zf1 has.

**Comment by Shardj** [comment]
There's no formal change log currently, but almost all changes come in through pull requests so you can look at the merge history there.

You're right though I should start listing changes when I make releases, I'll do that in the future, thank you for the feedback!

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/blob/master/CHANGELOG.md @func0der
