### ISSUE TITLE
controller->redirect('HTTP://DOMAIN.COM') treated as relative URL

### ISSUE THREAD

**Issue by brendandebeasi** [Shardj/zf1-future#24]
library/Zend/Controller/Action/Helper/Redirector.php:366

`if (!preg_match('|^[a-z]+://|', $url)) {`
should be
`if (!preg_match('|^[a-z]+://|i', $url)) {`

$controller->redirect('HTTP://DOMAIN.COM') is treated as a relative URL and appended to current URL instead of being treated as an absolute

**Comment by Shardj** [comment]
Sorted, thanks. In the future PR's are preferred just as it makes my life easier
