### ISSUE TITLE
PHP 8.1: Unknown named parameter $match in .../Zend/Form/Element.php on line 2119

### ISSUE THREAD

**Issue by topicode** [Shardj/zf1-future#246]
With the latest release `1.21.3` the following MWE:

    <?php
    
    require __DIR__ . "/vendor/autoload.php";
    
    $oForm = new Zend_Form();
    $oForm->addElement("text", "preg-test", [
        "label"   => "preg-test",
        "filters" => [
            [
                "PregReplace",
                [
                    "match"   => "/[\,\.].*/",
                    "replace" => "",
                ],
            ],
        ],
    ]);
    
    var_dump($oForm->isValid(["preg-test" => "oops"]));

 produces the following error:

    Fatal error: Uncaught Error: Unknown named parameter $match in /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php on line 2119
    
    Error: Unknown named parameter $match in /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php on line 2119
    
    Call Stack:
    0.0001     393320   1. {main}() /var/www/mwe/index.php:0
    0.0048    1216544   2. Zend_Form->isValid($data = ['preg-test' => 'oops']) /var/www/mwe/index.php:19
    0.0049    1231424   3. Zend_Form_Element->isValid($value = 'oops', $context = ['preg-test' => 'oops']) /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form.php:2296
    0.0049    1231424   4. Zend_Form_Element->getValue() /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php:1370
    0.0049    1231456   5. Zend_Form_Element->_filterValue($value = 'oops', $key = 'oops') /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php:610
    0.0049    1231456   6. Zend_Form_Element->getFilters() /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php:593
    0.0049    1231456   7. Zend_Form_Element->_loadFilter($filter = ['filter' => 'PregReplace', 'options' => ['match' => '/[\\,\\.].*/', 'replace' => '']]) /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php:1778
    0.0051    1243264   8. ReflectionClass->newInstanceArgs($args = ['match' => '/[\\,\\.].*/', 'replace' => '']) /var/www/mwe/vendor/shardj/zf1-future/library/Zend/Form/Element.php:2119

With the previous version `1.21.2` I get the following (expected) output:

    /var/www/mwe/index.php:19:
    bool(true)

The relevant code currently is in its original form (i.e. as from the Zend maintainers), because the previous change has been reverted for version `1.21.3`.

The current code is as follows:
https://github.com/Shardj/zf1-future/blob/a6dd6202fbada614ff1c58d9f599d5cfbd1b3256/library/Zend/Form/Element.php#L2117-L2122
And line of code as working for me was (note the wrapping of the argument in `[...]`:
https://github.com/Shardj/zf1-future/blob/98fbceb67b957735f108012787b6d75bd066dfa1/library/Zend/Form/Element.php#L2119

So for this case it is irrelevant if the options are passed as an array or as multiple arguments - at least before PHP 8 and its named parameters. The reason is that the PregReplace filter checks `func_get_args()` if the first parameter is not an array.
But with named parameters we have the problem that now a 'match' parameter and a 'replace' parameter are expected in the constructors' parameter list which are not there, because there is only a single `$options` parameter.

The problem here seems to be that the provided `options` should ideally be passed as an array (the `$options` array), but are not (and never were), and I don't know what else could break if the reverted change is being reverted back (to the `1.21.2` implementation). I think, it should be save to pass the options as array, since then the order of the options does not matter anymore, but I haven't checked that yet.

**Comment by Jimbolino** [comment]
I'm not sure if you or @siCoUK is right in this case.
https://github.com/Shardj/zf1-future/pull/186#issuecomment-1060931720

**Comment by topicode** [comment]
After reading the linked comment, I think that @SiCoUK is right, since he has a use case were the `[]`-wrapped version breaks.

But I think we should continue the discussion in #243, since that was opened earlier, and close this issue as a duplicate.
