### ISSUE TITLE
An extra var_dump has been left in the last changes

### ISSUE THREAD

**Issue by ricardoacosta290** [Shardj/zf1-future#254]
An extra var_dump has been left in the last changes https://github.com/Shardj/zf1-future/commit/621462411df65dd152f3de3501e1a1c72d038b8e

https://github.com/Shardj/zf1-future/blob/4d885d789c882627c20f4cb7b5e9130c8b21c7ec/library/Zend/Http/Response.php#L694

**Comment by topicode** [comment]
I could create a PR for this, but that seems a bit like overkill, doesn't it?

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/commit/fb49491963d3822aefb11e23fb6847adda673f92
