### ISSUE TITLE
Depreciation message with strtoupper 

### ISSUE THREAD

**Issue by krytenuk** [Shardj/zf1-future#259]
I found a depreciation message with `strtoupper` in the file `library/Zend/Form.php` when using PHP 8.1. The message occurs when `$type` is `null`. I have forked and created a fix, please see https://github.com/Shardj/zf1-future/compare/master...krytenuk:zf1-future:master#diff-b0800a50c63eeb488409dce71ec9b561f5c2db25db63dd248a3d9a50d9d1267d.

**Comment by glensc** [comment]
you should send a pull request then

**Comment by krytenuk** [comment]
Sorry, new to git. https://github.com/Shardj/zf1-future/pull/260

**Comment by glensc** [comment]
git != github
