### ISSUE TITLE
Parameter type "callback" in php doc blocs

### ISSUE THREAD

**Issue by gn-mtrlitza** [Shardj/zf1-future#264]
Hi there,

is it correct that there are multiple occurrences of the parameter type "callback" in the php doc blocks? For example https://github.com/Shardj/zf1-future/blob/master/library/Zend/EventManager/GlobalEventManager.php#L98
Our PHPStan is complaining about it and according to https://phpstan.org/writing-php-code/phpdoc-types#basic-types, I think that it needs to be changed to "callable".
If so, I would apply a PR.

Thanks
Michael

**Comment by gn-mtrlitza** [comment]
I created PR https://github.com/Shardj/zf1-future/pull/266 for this

**Comment by Shardj** [comment]
Merged
