### ISSUE TITLE
PHPUnit testing - mcrypt deprecation notices

### ISSUE THREAD

**Issue by develart-projects** [Shardj/zf1-future#270]
Since UT9 is merged, I'm trying to use them for regression testing. This is however hampered  by tons of deprecation notices. Partially these are correctly raised, especially for some conversions, but we have mainly mcrypt-related ones. As mcrypt is deprecated at all, my suggestion is to simply remove any mcrypt related tests.

If anyone has better idea how to deal with it, write it down pls, thanks.

**Comment by hungtrinh** [comment]
May be you run php 8.2 ?
Please more detail about php version, your  test command.
