### ISSUE TITLE
Zend_Mail : html emails are not correct in php8.1

### ISSUE THREAD

**Issue by svansteenkiste** [Shardj/zf1-future#274]
When trying to send html email in php7.4, everything works fine, but when changing to php8.1, html is shown as plain text instead of well formatted html email

**Comment by hungtrinh** [comment]
Please provide a code snippet to reproduce it 
or better please contribute test case like  [Zend_Mail_MailTest ::testGetJustBodyHtml()](https://github.com/Shardj/zf1-future/blob/master/tests/Zend/Mail/MailTest.php#L679)

**Comment by svansteenkiste** [comment]
Hi,

see snippet below:

<?php
  $mail = new Zend_Mail('UTF-8');
        
        $html = '<!DOCTYPE html>
<html>
    <body>
	<h1>TEST MESSAGE</h1>
        <table width="100%" border="0" align="center" valign="top" cellpadding="0" cellspacing="0">


            <tbody>
                <tr>
                    <td align="center" valign="top"><table width="650" border="0" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td><br>
                                        <br></td>
                                </tr>
                                <tr>
                                    <td align="center" valign="top"><img src="https://www.d-nailbar.be/OG_d-nailbar.jpg" height="150" alt="ALT Omschrijving"/></td>                                    
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <td style="background-color: #64254f;" class="title">this is a title</td>
                                </tr>                                
                            </tbody>
                        </table></td>
                </tr>
            </tbody>
        </table>
    </body>
</html>';
 
        
      $mail->setBodyHtml($html);
        $mail->setFrom($emailFrom, 'stijn');
        $mail->addTo($emailTo);
       $mail->setSubject('TEST koekoek');
 
       
        
        $mail->send();

**Comment by svansteenkiste** [comment]
Hi,

see snippet below:

<?php
  $mail = new Zend_Mail('UTF-8');
        
        $html = '<!DOCTYPE html>
<html>
    <body>
	<h1>TEST MESSAGE</h1>
        <table width="100%" border="0" align="center" valign="top" cellpadding="0" cellspacing="0">


            <tbody>
                <tr>
                    <td align="center" valign="top"><table width="650" border="0" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td><br>
                                        <br></td>
                                </tr>
                                <tr>
                                    <td align="center" valign="top"><img src="https://www.d-nailbar.be/OG_d-nailbar.jpg" height="150" alt="ALT Omschrijving"/></td>                                    
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <td style="background-color: #64254f;" class="title">this is a title</td>
                                </tr>                                
                            </tbody>
                        </table></td>
                </tr>
            </tbody>
        </table>
    </body>
</html>';
 
        
      $mail->setBodyHtml($html);
        $mail->setFrom($emailFrom, 'stijn');
        $mail->addTo($emailTo);
       $mail->setSubject('TEST koekoek');
 
       
        
        $mail->send();

**Comment by svansteenkiste** [comment]
well, this is most strange, because when i run this script in php7.4, it works fine.

**Comment by hungtrinh** [comment]
So which smtp server do you use Mr @svansteenkiste ?

**Comment by svansteenkiste** [comment]
i'm using Zend/Mail/Transport/Sendmail.php

**Comment by hungtrinh** [comment]
Oops look like internal bug of php 8.x.

https://github.com/Shardj/zf1-future/blob/bc1be9c5799009a3335c9d87c2d15ea05963a621/library/Zend/Mail/Transport/Sendmail.php#L102-L107

Reference: 

- https://github.com/php/php-src/issues/8086
- https://www.drupal.org/project/drupal/issues/3270647

**Comment by svansteenkiste** [comment]
i modified this on line 106:

str_replace("\n", "\r\n", $this->header);

Mail is now ok !
I think it has something to do with LF characters from mail headers

**Comment by svansteenkiste** [comment]
Thx for pointing me the right direction ;-)

**Comment by hungtrinh** [comment]
You’re welcome

**Comment by jakubprokopec** [comment]
@svansteenkiste  It's the Zend\Mail\Transport\Abstract and

    /**
     * EOL character string used by transport
     * @var string
     * @access public
     */
    public $EOL = "\r\n";

Just in case you didn't found the exact problem yet.

**Comment by svansteenkiste** [comment]
@jakubprokopec indeed, but in Zend\Mail\Transport\Sendmail you also have this
/**
     * EOL character string
     * @var string
     * @access public
     */
    public $EOL = PHP_EOL;


maybe better to remove here?

**Comment by jakubprokopec** [comment]
@svansteenkiste Totally... Thank you!

**Comment by ToonSpinISAAC** [comment]
FYI we have found that this issue may cause AWS Simple Email Service (SES) to reject mail with the message: "554 Transaction failed: Nested group".

Just commenting this in the hopes that someone stumbles upon this when trying to Google it, because that particular error message is not easy to Google.

**Comment by ADDISON74** [comment]
From what I can see, those who faced this issue chose to make individual changes in the ZF1-Future file. May I ask why a PR was not pushed to fixe the issue for the others who have not faced it yet? In a test configuration I managed to reproduce this problem with all the email messages sent by OpenMage.

**Comment by develart-projects** [comment]
Scheduled for 1.23.0 release, awaiting 2 more PRs resp. PR owners to take some action.

**Comment by develart-projects** [comment]
1.23.0 released
