### ISSUE TITLE
Test fixture file tests/Zend/Paginator/_files/test.sqlite modified everytime run unittest

### ISSUE THREAD

**Issue by hungtrinh** [Shardj/zf1-future#283]
## Expected Behavior

https://github.com/Shardj/zf1-future/blob/master/tests/Zend/Paginator/_files/test.sqlite doesn't change after run unit test `Zend_Paginator_Adapter_DbSelectTest::testSelectHasAliasedColumns`
## Current Behavior

https://github.com/Shardj/zf1-future/blob/master/tests/Zend/Paginator/_files/test.sqlite modified everytime run unittest `Zend_Paginator_Adapter_DbSelectTest::testSelectHasAliasedColumns`
https://github.com/Shardj/zf1-future/blob/bc1be9c5799009a3335c9d87c2d15ea05963a621/tests/Zend/Paginator/Adapter/DbSelectTest.php#L304-L369

## Steps to Reproduce

1. Git check status before run test
    ```bash
    $ git status
    On branch master
    Your branch is up to date with 'origin/master'.

    nothing to commit, working tree clean
    ```
1. Run test `Zend_Paginator_Adapter_DbSelectTest::testSelectHasAliasedColumns`
    ```bash
    $ docker run -u "$(id -u):$(id -g)" --rm -w $(pwd) -v $(pwd):$(pwd) php:8.2-rc-cli-alpine -d memory_limit=-1 ./bin/phpunit -v --bootstrap tests/TestHelper.php --testdox --filter Zend_Paginator_Adapter_DbSelectTest::testSelectHasAliasedColumns tests/Zend/Paginator/Adapter/DbSelectTest.php
    PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

    Runtime:       PHP 8.2.0RC6

    Zend_Paginator_Adapter_Db Select
     ✔ Select has aliased columns [6.37 ms]

    Time: 00:00.009, Memory: 6.00 MB

    OK (1 test, 0 assertions)
    ```
1. Git check status after run test
    ```bash
    $ git status
    On branch master
    Your branch is up to date with 'origin/master'.

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git restore <file>..." to discard changes in working directory)
            modified:   tests/Zend/Paginator/_files/test.sqlite
    ```

## Possible Solution

1. Replace this line of code 

    https://github.com/Shardj/zf1-future/blob/bc1be9c5799009a3335c9d87c2d15ea05963a621/tests/Zend/Paginator/Adapter/DbSelectTest.php#L306-L306

    by

    ```php
    $db = new Zend_Db_Adapter_Pdo_Sqlite([
         'dbname' => dirname(__FILE__) . '/../_files/test-write-tmp.sqlite'
    ]);
    ```
1. add line `tests/Zend/Paginator/_files/test-write-tmp.sqlite` into https://github.com/Shardj/zf1-future/blob/bc1be9c5799009a3335c9d87c2d15ea05963a621/.gitignore#L1-L24

**Comment by glensc** [comment]
Now https://github.com/Shardj/zf1-future/pull/284 creates new `tests/Zend/Paginator/_files/test-write-tmp.sqlite` file
but what about `tests/Zend/Paginator/_files/test.sqlite` that I addresed in the first place?

also, please add a link (to issue body) to the original discussion about `tests/Zend/Paginator/_files/test-write-tmp.sqlite`

**Comment by hungtrinh** [comment]
> tests/Zend/Paginator/_files/test.sqlite
what's in it anyway? perhaps it should be reverted to value in [59ede18](https://github.com/Shardj/zf1-future/commit/59ede1801c697a8e2a8051acdaed5be8eb4a59be)?

Mr @glensc yes it should be reverted to value in [59ede18](https://github.com/Shardj/zf1-future/commit/59ede1801c697a8e2a8051acdaed5be8eb4a59be).

Or Keeping current state of `tests/Zend/Paginator/_files/test.sqlite` doesn't give any ill effects, all test case passed

**Comment by glensc** [comment]
I checked `tests/Zend/Paginator/_files/test.sqlite` at 65c1385dce02591d31b1165283ed7f8e018badfd (current) and 59ede1801c697a8e2a8051acdaed5be8eb4a59be (oldest) and the sql dump is the same.

```
$ echo .dump | sqlite3 tests/Zend/Paginator/_files/test.sqlite > dump.sql
```

- [dump.sql.txt](https://github.com/Shardj/zf1-future/files/10032974/dump.sql.txt) 17K

but what for the file is needed then? can it be just removed now?

**Comment by hungtrinh** [comment]
Mr @glensc it can not be just removed

it needed for:
1. Almost test case inside `Zend_PaginatorTest` 
  https://github.com/Shardj/zf1-future/blob/59ede1801c697a8e2a8051acdaed5be8eb4a59be/tests/Zend/PaginatorTest.php#L130-L157 Like that
   https://github.com/Shardj/zf1-future/blob/59ede1801c697a8e2a8051acdaed5be8eb4a59be/tests/Zend/PaginatorTest.php#L228-L235
1. Almost test case inside `Zend_Paginator_Adapter_DbSelectTest`
  https://github.com/Shardj/zf1-future/blob/355b75a5f5af60380e803cbf9a5f8175c04aad00/tests/Zend/Paginator/Adapter/DbSelectTest.php#L77-L96  Like that https://github.com/Shardj/zf1-future/blob/355b75a5f5af60380e803cbf9a5f8175c04aad00/tests/Zend/Paginator/Adapter/DbSelectTest.php#L218-L228

**Comment by glensc** [comment]
ok. thanks for the answer. just the other tests don't modify the database. i suppose.

**Comment by hungtrinh** [comment]
Yep, that correct, those test case read data only don't change sqlite file's content.
