### ISSUE TITLE
Boolean values in ini config files need to be parsed as actual bool values [php 8.1]

### ISSUE THREAD

**Issue by crankycyclops** [Shardj/zf1-future#288]
I'm using zf1-future on PHP 8.1 with the following PDO setting in application.ini:

`resources.db.params.driver_options.1000 = true`

This parses to a string value "1" in the config, and so on line 128 of Zend/Db/Adapter/Pdo/Abstract.php, I get this error:

"Attribute value must be of type bool for selected attribute, string given"

For newer versions of PHP, boolean and integer values should be distinguishable from each other. Maybe values of "true"/"false" or "t"/"f" can be interpreted as boolean true or false, while values of "1"/"0" can be interpreted as integer 1/0?

**Comment by crankycyclops** [comment]
I was able to fix this by adding the following line to public/index.php before the instantiation of Zend_Application:
`Zend_Application::setConfigParserOptions(['scannerMode' => INI_SCANNER_TYPED]);`

Not sure if this should be a default or not. Maybe not, since it might break existing applications.

**Comment by develart-projects** [comment]
@crankycyclops is this with strict_types = 1 ?

**Comment by crankycyclops** [comment]
> 

No, I don't have strict_types enabled anywhere.

**Comment by crankycyclops** [comment]
> @crankycyclops is this with strict_types = 1 ?

@develart-projects No, I don't have strict_types enabled anywhere.

**Comment by develart-projects** [comment]
> Not sure if this should be a default or not. Maybe not, since it might break existing applications.

That's exactly what I'm thinking (especially if there is optional switch for that). Leaving here for a discussion.

**Comment by develart-projects** [comment]
Seems nobody is interested, so closing.
