### ISSUE TITLE
[PHP7.0] htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by francesco-loreti** [Shardj/zf1-future#29]
**Cause:**
> "htmlspecialchars() expects parameter 1 to be string, array given" into 
> Zend/View/Abstract.php line 905

**Solution:**
`
         if (in_array($this->_escape, array('htmlspecialchars', 'htmlentities'))) {
            return call_user_func($this->_escape, "{$var}", ENT_COMPAT, $this->_encoding);
        }

        if (1 == func_num_args()) {
            return call_user_func($this->_escape, "{$var}");
        }

`

**Comment by Shardj** [comment]
If you're making a PR feel free to skip out on creating an issue, this is only a small repo so there's no need for both
