### ISSUE TITLE
State of PHP 8.1 support

### ISSUE THREAD

**Issue by fballiano** [Shardj/zf1-future#293]
Hi everyone,
what's the state of PHP8.1 support, we'd like to integrate this package into https://github.com/OpenMage/magento-lts but we're supporting PHP8.1 so we'd like to be on-par here.

I see a person created a 8.1 fork of this repo https://github.com/actionstep/zf1-future what's up with that?

Thanks everybody!

**Comment by alexgit2k** [comment]
There have been several changes for PHP 8.1 deprecation notices, notably #189, #214, #212.
We are running zf1-future since March on PHP 8.1, it's working without problems, but of course we do not use all functions, so I can not say if everything works.

**Comment by Shardj** [comment]
While I started this code base, I no longer work on a project that uses it. However before I left that project I was using this code base with PHP 8.1 for a year and then used it with PHP 8.2 for a month
