### ISSUE TITLE
PHP Fatal error:  Declaration of Zend_Rest_Route::assemble($data = Array, $reset = false, $encode = true) must be compatible with Zend_Controller_Router_Route_Module::assemble($data = Array, $reset = false, $encode = true, $partial = false)

### ISSUE THREAD

**Issue by simogrima** [Shardj/zf1-future#3]
Zend Framework 1 reaches its End of Life (EOL) and is no longer maintained.
No Pull Requests will be accepted.

https://framework.zend.com/blog/2016-06-28-zf1-eol.html

**Comment by Shardj** [comment]
I'm very aware that zf1 reached EOL, that's why this fork exists. Also your error message by itself isn't of much use, I'll close this until you provide something more helpful.

**Comment by simogrima** [comment]
Shardj,
I I tried to use your fork but I get that error message.

**Comment by Shardj** [comment]
Could you provide a stack trace? And the code you're using to bootstrap the framework?

**Comment by simogrima** [comment]
The proble is in the boostrap whi i try to init rest route

    protected function _initRoutes()
    {
        $this->bootstrap("frontController");
        $front = $this->getResource("frontController");

        $front->getRouter()->addConfig(new Zend_Config_Ini(APPLICATION_PATH . "/configs/routes.ini"), "routes");
        
        $restRoute = new Zend_Rest_Route($front, array(), array('it' => array('rest_cache')  ));
        $front->getRouter()->addRoute('rest', $restRoute);         
    }

**Comment by Shardj** [comment]
Should now be fixed on master, I went and looked at some forks of my branch and this issue was sorted on a couple of them so I merged one in.
