### ISSUE TITLE
PHPdocs: missleading "provides a fluent interface"

### ISSUE THREAD

**Issue by sreichel** [Shardj/zf1-future#302]
A lot of phpdocs say return provides a fluent interface, but it does not.

E.g. https://phpstan.org/r/8f5203f0-1931-40b7-928a-b6655d55d21b

Return type should be either `$this` (or `static`).

PR ready,

**Comment by Shardj** [comment]
Could you link the PR? I don't see any from you for this class

**Comment by sreichel** [comment]
Its not pushed yet. What do you prefer - `$this` or `static`?

**Comment by sreichel** [comment]
@Shardj if you have time, please check the official patches of Magento and let me know if you want me to create PRs ... https://github.com/OpenMage/magento-lts/tree/1.9.4.x/patches (first can be ignored)

**Comment by ADDISON74** [comment]
@sreichel - would it be OK if we propose those changes in this repository and thus we would get rid of the use of patches?

**Comment by sreichel** [comment]
I will create the corresponding PRs later.

**Comment by sreichel** [comment]
@Shardj thanks for merging.

There are three "Magento-patches" left ...  i'll add them next days.
