### ISSUE TITLE
Starting from PHP 8.1.14 Zend_Date creates "Unknown or bad timezone"

### ISSUE THREAD

**Issue by michiel-van-den-anker** [Shardj/zf1-future#304]
We create a `Zend_Date` with the timezone `'Europe/Amsterdam'`. Internally this gets converted to `'Etc/GMT+11'`. This subsequently is passed into `timezone_open` where it fails from PHP 8.1.14 and upwards.

Example: https://onlinephp.io?s=VYyxCsIwFEX3Qv_hkiUt0oTOSkVQnHRycimhfZgOeQnN6-LXm624nOFy7jmdk091VVfW4k08j1cnBNlWztC3bY2J7CVkoXV2QWNhiWWXyd4fr0PfazieIZ64YMnwLiXibIxBXdHkI5Qsgb6RaSwpbvZri26AgsG_oHZDtd3wIXm6QE17_AE%2C&v=8.2.1%2C8.1.14%2C8.0.27%2C8.1.13%2C8.0.26

EDIT: I'm pretty sure this is a PHP issue not a zf1-future issue

**Comment by michiel-van-den-anker** [comment]
So yeah this is it: https://github.com/php/php-src/issues/10218

In that thread one person mentions that something like 'Etc/GMT+11' is possibly not forward compatible. This is linked: https://www.php.net/manual/en/timezones.others.php

Closing!

**Comment by derickr** [comment]
FWIW, this is now fixed for PHP 8.1.15 and PHP 8.2.2 as per https://github.com/php/php-src/commit/d12ba111e03fa4e6d76a66a029f5dbe6265b1ea9
