### ISSUE TITLE
Avoid using deprecated "Etc/GMT±n" timezones in Zend_Date

### ISSUE THREAD

**Issue by elidrissidev** [Shardj/zf1-future#305]
The bug that was happening lately in PHP 8.1.14 and 8.2.1 revealed that `Zend_Date` class was using some old and [deprecated timezones](https://www.php.net/manual/en/timezones.others.php) when trying to guess a timezone from a string date (e.g. `2022-12-27T08:15:24-08:00`), this was happening in the constructor so there was no way around it even if you plan to `setTimezone()` later after constructing the `Zend_Date` object.

Although it has been reported that the bug was resolved in the upcoming PHP version, it still would be good to address this issue to avoid any potential problems in the future. But I'm still not sure how to address this.

Related links:
- See https://github.com/OpenMage/magento-lts/issues/2915#issuecomment-1377432874
- See https://github.com/Shardj/zf1-future/issues/304

**Comment by ADDISON74** [comment]
We have to appreciate the fact that @derickr responded very quickly today to our reports and solved the issue. But since we are warned not to use timezone formats such as GMT-n or GMT+n, ZF1-Future must be updated too, especially since it has meanwhile become an important piece for the OpenMage project.

**Comment by glensc** [comment]
duplicate:
- https://github.com/Shardj/zf1-future/issues/304

**Comment by elidrissidev** [comment]
Yes I know but that issue got closed already. PHP will fix this in the next version, but I'm wondering if something can be done about it to replace those timezones with the appropriate ones.

**Comment by ADDISON74** [comment]
I quote the observation made by @sreichel in the OpenMage repository:

"ZF1 uses this file https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml"

**Comment by sreichel** [comment]
i think playing around with the file doesn't make sense. rather wait for the next release and avoid 8.1.4/8.2.1?

**Comment by hungtrinh** [comment]
Please close this issue,  current github action php ver is 8.1.15, 8.2.2 so issue above fixed:

- https://github.com/Shardj/zf1-future/actions/runs/4171642686/jobs/7221797554#step:7:31
- https://github.com/Shardj/zf1-future/actions/runs/4171642686/jobs/7221797699#step:7:3

**Comment by elidrissidev** [comment]
> Although it has been reported that the bug was resolved in the upcoming PHP version, it still would be good to address this issue to avoid any potential problems in the future. But I'm still not sure how to address this.
