### ISSUE TITLE
support "samesite" cookie attribute in Zend_Http_Header_SetCookie

### ISSUE THREAD

**Issue by staabm** [Shardj/zf1-future#315]
would be great if the `Zend_Http_Header_SetCookie` would allow setting a samesite cookie attribute

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by hungtrinh** [comment]
Please feel free to contribute your own ideas by make PR ^^

**Comment by develart-projects** [comment]
@staabm I'm happy to merge, if you will find some time to add that :)

**Comment by develart-projects** [comment]
Completed, will be released in 1.24.0
