### ISSUE TITLE
Creation of dynamic property Core_AdminIndexController::$contexts is deprecated   - Php 8.2.0

### ISSUE THREAD

**Issue by vijaygarg-ahead** [Shardj/zf1-future#316]
Can anyone provide me the solution for this warning log:

`Creation of dynamic property Core_AdminIndexController::$contexts is deprecated (libraries\Zend\Controller\Action\Helper\ContextSwitch.php) [1148]`

**Comment by Sdfendor** [comment]
See #307 this is a widespread issue that needs to be resolved for ZF1-Future to work with 8.2.

**Comment by Shardj** [comment]
Closing as duplicate
