### ISSUE TITLE
I just have a problem

### ISSUE THREAD

**Issue by cormansa** [Shardj/zf1-future#318]
The file exist in the specified path and right are good : 
-rw-r-----. 1 root apache 745 Feb  2 13:36 /mnt/www/bascule/application/views/scripts/error/error.phtml

so I don't know where is the problem (zf 1.22)

`Uncaught Zend_View_Exception: script 'error/error.phtml' not found in path (/mnt/www/bascule/application/views/scripts/:./views/scripts/) in /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/View/Abstract.php:986 Stack trace: #0 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/View/Abstract.php(882): Zend_View_Abstract->_script('error/error.pht...') #1 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/Helper/ViewRenderer.php(910): Zend_View_Abstract->render('error/error.pht...') #2 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/Helper/ViewRenderer.php(931): Zend_Controller_Action_Helper_ViewRenderer->renderScript('error/error.pht...', NULL) #3 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/Helper/ViewRenderer.php(970): Zend_Controller_Action_Helper_ViewRenderer->render() #4 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch() #5 /mnt/www/lib/ in /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Plugin/Broker.php on line 335`

**Comment by glensc** [comment]
@cormansa edit your bug report and put pastes to markdown code fence

**Comment by hungtrinh** [comment]
@cormansa 

Above file privileges it's ok if you use apache web sever (not nginx)
 
Quick fix please try this first: `chmod +r /mnt/www/bascule/application/views/scripts/error/error.phtml`
if not ok so may be your problem, it's something like that https://www.svnlabs.com/blogs/centos-7-selinux-apache-php-writeaccess-permission/

**Comment by glensc** [comment]
you may also need to check **every** parent directory of the file

1. /mnt/www/bascule/application/views/scripts/error/
2. /mnt/www/bascule/application/views/scripts/
3. /mnt/www/bascule/application/views/
4. ...and so on

best to check is to sudo to target user, i.e apache:

```
sudo -u apache head -n1 /mnt/www/bascule/application/views/scripts/error/error.phtml
```

check first what your webserver user is with `ps -ef`

**Comment by cormansa** [comment]
C2

Hi,

The quick fix doesn’t work.
I looked the link, but I have no selinux error in log file.

Here the full stacktrace from /var/log/php-fpm/www-error.log

[07-Feb-2023 10:31:33 Europe/Brussels] PHP Fatal error:  Uncaught Zend_View_Exception: script 'error/error.phtml' not found in path (/mnt/www/bascule/application/views/scripts/:./views/scripts/) in /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/View/Abstract.php:986
Stack trace:
#0 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/View/Abstract.php(882): Zend_View_Abstract->_script('error/error.pht...')
#1 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/Helper/ViewRenderer.php(910): Zend_View_Abstract->render('error/error.pht...')
#2 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/Helper/ViewRenderer.php(931): Zend_Controller_Action_Helper_ViewRenderer->renderScript('error/error.pht...', NULL)
#3 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/Helper/ViewRenderer.php(970): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /mnt/www/lib/ in /mnt/www/lib/zf1-future-release-1.22.0/library/Zend/Controller/Plugin/Broker.php on line 335

I read on internet that there are a command for display error without using error.phtml.
https://stackoverflow.com/questions/13248843/uncaught-exception-zend-view-exception-with-message-script-error-error-phtml

but I don’t know how to implement that on my web app.

Regards,



De : Hưng Trịnh ***@***.***>
Envoyé : mardi 7 février 2023 09:43
À : Shardj/zf1-future ***@***.***>
Cc : Stephane PURNELLE ***@***.***>; Mention ***@***.***>
Objet : Re: [Shardj/zf1-future] I just have a problem (Issue #318)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

@cormansa<https://github.com/cormansa>

Above file privileges it's ok if you use apache web sever (not nginx)

Quick fix please try this first: chmod +r /mnt/www/bascule/application/views/scripts/error/error.phtml
if not ok so may be your problem, it's something like that https://www.svnlabs.com/blogs/centos-7-selinux-apache-php-writeaccess-permission/

**Comment by cormansa** [comment]
C2

I found this :

[07-Feb-2023 10:30:08 Europe/Brussels] PHP Warning:  Declaration of IndexController::init() should be compatible with BaseController::init($title = 'BaseCollec...') in /mnt/www/bascule/application/controllers/IndexController.php on line 3
[07-Feb-2023 10:30:08 Europe/Brussels] PHP Warning:  log() expects parameter 1 to be float, string given in /mnt/www/bascule/application/controllers/IndexController.php on line 9

Is it normal ?

regards


De : Hưng Trịnh ***@***.***>
Envoyé : mardi 7 février 2023 09:43
À : Shardj/zf1-future ***@***.***>
Cc : Stephane PURNELLE ***@***.***>; Mention ***@***.***>
Objet : Re: [Shardj/zf1-future] I just have a problem (Issue #318)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

@cormansa<https://github.com/cormansa>

Above file privileges it's ok if you use apache web sever (not nginx)

Quick fix please try this first: chmod +r /mnt/www/bascule/application/views/scripts/error/error.phtml
if not ok so may be your problem, it's something like that https://www.svnlabs.com/blogs/centos-7-selinux-apache-php-writeaccess-permission/

**Comment by glensc** [comment]
@cormansa. can you edit your posts to remove cruft from emails?

and seems you totally omitted my reply:
- https://github.com/Shardj/zf1-future/issues/318#issuecomment-1420436670

and post terminal output of the commands if you want to show proof the file is readable for webserver user.

**Comment by cormansa** [comment]
It’s work…

Your comment #318 help me.

thank you and I'm happy that someone continue to maintain zf1
