### ISSUE TITLE
LDAP Auth Adapter not working in PHP 8 under release 1.22

### ISSUE THREAD

**Issue by reecelikesramen** [Shardj/zf1-future#345]
I notice this has been fixed in master, but as of release 1.22.0 it is still broken. Will there be a patch for packagist with this so projects don't have to clone the repo into source to work after an upgrade?

See commit 5446af3466d1fc3faa32a708af2cdc9baf9fc11a vs master.

**Comment by codefroggie** [comment]
Is there a fix for this yet? LDAP not working with release 1.22 and  PHP 8.1.18.

**Comment by reecelikesramen** [comment]
If you set up your project to use a specific commit, as mentioned in my comment, or master it will work. I was able to get LDAP working in PHP 8.2

**Comment by MartinBichsel** [comment]
LDAP Auth Adapter was not working in PHP 8.1 under release 1.22 but Marcin Gill made important corrections in January and February. I was able to successfully test all my use cases for the recent commit 7fa9c5f5. Security issues urge me to switch to PHP 8.1 Why haven't we seen a release for quite  a long time? When is the next release planned.

**Comment by gyflorand** [comment]
LDAP resources are migrated to LDAP objects from php:8.1. Can we expect fixes for these?

**Comment by gyflorand** [comment]
Can we expect a patch for packagist?

**Comment by develart-projects** [comment]
@reecelikesramen @gyflorand released today in 1.22.1
