### ISSUE TITLE
Slowness after php 8.1 migration

### ISSUE THREAD

**Issue by andersonfelizari** [Shardj/zf1-future#346]
Hello

I have an application running with PHP 7.4 and now I migrated to 8.1 and I noticed that my queries in Mysql using PDO are 3 times slower.

Job that runs in 7.8s in php 7.4 is running in 21.5s in php 8.1 and following through newrelic what is taking longer are the queries.

Any tips on this?

**Comment by thoys** [comment]
I noticed you closed this issue, did you manage to get it solved? If yes how
