### ISSUE TITLE
PHP 8.2 - null to string conversion deprecation issue in Zend_Validate_File_Extension

### ISSUE THREAD

**Issue by pisc-software** [Shardj/zf1-future#351]
Zend_Validate_File_Extension needs a fix where a string variable is set to null in the class, throwing deprecation messages as on PHP 8.2 the null value is not automatically converted to an empty string anymore:

```
File: lib/Zend/Validate/File/Extension.php (135)
    /**
     * Sets the file extensions
     *
     * @param  string|array $extension The extensions to validate
     * @return Zend_Validate_File_Extension Provides a fluent interface
     */
    public function setExtension($extension)
    {
        // FIX: Set _extension to empty string instead of null
        $this->_extension = '';
        $this->addExtension($extension);
        return $this;
    }
```

**Comment by hungtrinh** [comment]
@pisc-software please feel free to make PR

**Comment by develart-projects** [comment]
I'm on it. You can't simply change tu empty string, because there is null comparsion in the code.

**Comment by develart-projects** [comment]
Validator is screwed up a bit more than expected, by previous commits. Once setting string, then expecting array, then null. I'll revert recent updates and fix the problem itself, as described.

**Comment by develart-projects** [comment]
1.23.0 released

**Comment by pisc-software** [comment]
Thank you for the effort.
