### ISSUE TITLE
Documentation error - wrong param count in Http client adapter test file

### ISSUE THREAD

**Issue by ururk** [Shardj/zf1-future#355]
`/library/Zend/Http/Client/Adapter/Test.php`

```php
    /**
     * Connect to the remote server
     *
     * @param string  $host
     * @param int     $port
     * @param boolean $secure
     * @param int     $timeout
     * @throws Zend_Http_Client_Adapter_Exception
     */
    public function connect($host, $port = 80, $secure = false)
```

Four params are documented, but the function only take three. Obviously, this function doesn't do much - as stated at the top `without actually performing an HTTP request.`. Not critical, but noticed it.

**Comment by develart-projects** [comment]
https://github.com/Shardj/zf1-future/pull/364

**Comment by develart-projects** [comment]
1.23.0 released
