### ISSUE TITLE
Zend_Db_Adaper_PDO_Mysql complainting about variable types while setting PDO::ATTR_STRINGIFY_FETCHES via application.ini

### ISSUE THREAD

**Issue by roshanbudhathoki** [Shardj/zf1-future#382]
When application.ini is set with PDO::ATTR_STRINGIFY_FETCHES to false it solves the problem of automatic stringify of the fetches from zend_db .

```
[production]

resources.db.params.driver_options.17 = false
resources.db.params.profiler.enabled = true
```

But when following application.ini used it throws following error.

```
Attribute value must be of type bool for selected attribute, string given : 

hardj\\zf1-future\\library\\Zend\\Db\\Adapter\\Pdo\\Abstract.php","line":141

```
None of the values such as "false", 0, "0" work, they all trigger this exception.

This solves the problem of 
https://github.com/Shardj/zf1-future/issues/362

too.

**Comment by develart-projects** [comment]
Need to find it, but there is a setting for parsing ini file values as booleans. Need to be set to get it working properly. 
You can look into closed issues, or I'll find it later and add here.

**Comment by hungtrinh** [comment]
@roshanbudhathoki Maybe your php ver >= 8.1 so this solution works for you https://github.com/Shardj/zf1-future/issues/288#issuecomment-1322726449
