### ISSUE TITLE
Zend_Controller_Action_Helper_AjaxContext And Zend_Controller_Action_Helper_ContextSwitch

### ISSUE THREAD

**Issue by agarraud** [Shardj/zf1-future#395]
When i use ajax context with PHP 8.2

`
$this->_helper->ajaxContext
    ->addActionContext('widget-catalog', 'json')
    ->initContext();
`

And i have an error : 

Creation of dynamic property DashboardController::$ajaxable is deprecated

I found a commit : 
https://github.com/Shardj/zf1-future/commit/ae86354cc3f156d8ed2568b0520b342e47275ea2
but doesn't work with Zend_Controller_Action_Helper_AjaxContext because the name of contextKey is different

**Comment by develart-projects** [comment]
Fixed by https://github.com/Shardj/zf1-future/pull/376
