### ISSUE TITLE
iconv() Null Deprecation 

### ISSUE THREAD

**Issue by kiatng** [Shardj/zf1-future#398]
[type] => 8192:E_DEPRECATED
    [message] => iconv(): Passing null to parameter #3 ($string) of type string is deprecated
    [file] => .../shardj/zf1-future/library/Zend/Pdf/Resource/Font/Simple.php

https://github.com/Shardj/zf1-future/blob/f8018da6a411b5dc5c253d614c01d32b76e7f971/library/Zend/Pdf/Resource/Font/Simple.php#L268-L268

**Comment by sreichel** [comment]
Can you track it down, where it comes from? Maybe its easier to fix inside OpenMage?

**Comment by sreichel** [comment]
Nice. IMHO this can be closed.

(@kiatng o/c it could be also fixed here, but im a fan of simple as possible method signatures ... just assume strict types allowing only string arguments)

**Comment by kiatng** [comment]
Fixing here would make it easier for the dependents of zf1-future to upgrade to PHP8 or 9. But OK, it's the responsibility of the dependents and their plugins to fix all null deprecations.
