### ISSUE TITLE
Tag a new release for the latest php 7.4 fix(es)

### ISSUE THREAD

**Issue by Hikariii** [Shardj/zf1-future#40]
https://github.com/Shardj/zf1-future/commit/59fa1a8fc952443b30ab2a5b1be4ea1c8506d7c2 is needed for php 7.4 compatibility, but is not included in 1.16.0
Could you tag a new release from master?

**Comment by Shardj** [comment]
Sure thing

**Comment by Shardj** [comment]
https://github.com/Shardj/zf1-future/releases/tag/release-1.16.1
