### ISSUE TITLE
Correct and add return type / type declarations

### ISSUE THREAD

**Issue by kstenschke** [Shardj/zf1-future#42]
https://github.com/Shardj/zf1-future/blob/5f6ddecd7ba0093a7eeae3a20c51cafe9b3339ca/library/Zend/Db/Adapter/Abstract.php#L732

The existing DOC annotations in many cases are incomplete: e.g. see the linked fetchAll-method, which actually returns array|null and not array as annotated. 
Any chance to get those missing types declared (over time)?

**Comment by Shardj** [comment]
Over time? Sure, I have no issue with correcting these as they're reported. However this repo is just maintained as a side project, I'm not likely to bump into these myself and I won't be scouring the repo to try and figure out which return docblock typehints are incorrectly not mentioning that they're nullable.

Please feel free to make pull requests whenever you see one of these and I'll merge it as soon as I see it. I'll go and fix the fetchAll you've mentioned now.
