### ISSUE TITLE
Order of distinct and top is wrong

### ISSUE THREAD

**Issue by muuvmuuv** [Shardj/zf1-future#421]
When using both, distinct will come after "top 20" which results in an SQL error.

**Comment by develart-projects** [comment]
Anyone to create PR and test locally?

**Comment by muuvmuuv** [comment]
Does it have or need tests? We have it in production at one customer and no issues since i vreated the ticket so far

**Comment by develart-projects** [comment]
If it's already proven, then just create an PR pls.

**Comment by muuvmuuv** [comment]
Just created a pr. Wasn't able to run the sqlsrv tests ("test") but all other tests run well.
