### ISSUE TITLE
Zend_Validate::$zfBreakChainOnFailure is deprecated in /var/www/html/vendor/shardj/zf1-future/library/Zend/Form/Element.php on line 1229

### ISSUE THREAD

**Issue by salacr** [Shardj/zf1-future#422]
I'm getting this error:
`Zend_Validate::$zfBreakChainOnFailure is deprecated in /var/www/html/vendor/shardj/zf1-future/library/Zend/Form/Element.php on line 1229`

**Comment by develart-projects** [comment]
released 1.24.1 with fix
