### ISSUE TITLE
add TLSv1_3

### ISSUE THREAD

**Issue by jirapetr** [Shardj/zf1-future#427]
Please change library/Zend/Mail/Protocol/Smtp.php
.. 
if ($this->_secure == 'tls') {
            $this->_send('STARTTLS');
            $this->_expect(220, 180);
            if (!stream_socket_enable_crypto(
                $this->_socket,
                true,
                **STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT**
            )) {

**Comment by ADDISON74** [comment]
You can create a PR to solve the reported problem.

**Comment by PHPGangsta** [comment]
Adding TLS 1.3 totally makes sense, but dropping the other versions (STREAM_CRYPTO_METHOD_TLS_CLIENT|STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT) is a backwards-compatibility break that I would not want.

Please only add TLS 1.3 and don't drop the others. Or make it configurable if needed, with a default that preserves backwards compatibility.

**Comment by develart-projects** [comment]
Possibly a good note, pls open PR for that, I'll merge that, thanks.

**Comment by ADDISON74** [comment]
@develart-projects - I opened a PR for this request here following @PHPGangsta request.

**Comment by sreichel** [comment]
Closed with https://github.com/Shardj/zf1-future/pull/447?

**Comment by develart-projects** [comment]
released 1.24.1 with fix
