### ISSUE TITLE
deprecated passing null to strripos and rtrim with php 8.3

### ISSUE THREAD

**Issue by sirber** [Shardj/zf1-future#428]
( ! ) Deprecated: strripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/vendor/shardj/zf1-future/library/Zend/View/Helper/BaseUrl.php on line 110

( ! ) Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/shardj/zf1-future/library/Zend/View/Helper/BaseUrl.php on line 72

**Comment by ychateauvert** [comment]
May I introduce you to [cweagans/composer-patches](https://github.com/cweagans/composer-patches). You can check freerice-engine for an example but basically you can provide patches that will be applied during composer install/update.

**Comment by B3none** [comment]
I checked the file, and it looks like these issues have been resolved: https://github.com/Shardj/zf1-future/blob/master/library/Zend/View/Helper/BaseUrl.php

When's the last time you ran a composer update?

**Comment by sirber** [comment]
I'm on the latest 1.24 version, still having those issues.

**Comment by B3none** [comment]
I've got it running on 8.3.29 without any problems, can you give me an example snippet of what you're doing and I'll test it on my end

**Comment by ADDISON74** [comment]
A new release should be made public including this PR https://github.com/Shardj/zf1-future/pull/442 for testing ZF1-Future with PHP 8.4.

**Comment by sirber** [comment]
Related to #450

**Comment by develart-projects** [comment]
released 1.24.1 with fix
