### ISSUE TITLE
[question] Can I use npm or yarn for import javascript and css modules?

### ISSUE THREAD

**Issue by francesco-loreti** [Shardj/zf1-future#435]
Hello!

I'm asking here because I've already searched everywhere with no luck. 
I wanted to use npm or Yarn to import and, above all, keep the js and css libraries updated, avoiding having to check and download each time in the relevant folders in "/public". 
When I use npm (or yarn), it creates the "node_modules" folder. Is there a way you think I can tell Zend to draw resources from there? How does the "composer" do for the "vendor" folder. 

Thanks for any replies.

**Comment by develart-projects** [comment]
Search for .yarnrc

You need something like 
`--modules-folder public/static/components/`
