### ISSUE TITLE
New release required for fix of library/Zend/Pdf/Element.php

### ISSUE THREAD

**Issue by ramondelafuente** [Shardj/zf1-future#454]
Hi,

Release version `1.24.1` introduced a bug in Zend_Pdf, which was already caught and fixed in the following commit:
https://github.com/Shardj/zf1-future/commit/cf7527e993d86d90515cbe55388b5242b18dcc00

(the introduced $value variable causes the runtime to ignore __get('value'), which was proxying to $_value->value)

Is there a release planned for the fixed version? 

Thanks for all your efforts on supporting ZF1 for modern PHP versions :-)

**Comment by develart-projects** [comment]
fixed in 1.24.2

**Comment by colinmollenhour** [comment]
This line of code appears to be back in 1.24.3 even though it's not in master.. I downloaded the zip file from the Releases page and it is there..
