### ISSUE TITLE
Wrong version in library\Zend\Version.php 1.24.1

### ISSUE THREAD

**Issue by adolfo-ubs** [Shardj/zf1-future#455]
In version 1.24.1 it still appears older version 1.23.5

![imagen](https://github.com/user-attachments/assets/1e3f58ca-37f6-4966-93ba-3102e1d71556)

**Comment by ADDISON74** [comment]
We can correct this issue but not before solving this one https://github.com/Shardj/zf1-future/issues/454.

**Comment by develart-projects** [comment]
fixed in 1.24.2
