### ISSUE TITLE
Invalid required PHP version.

### ISSUE THREAD

**Issue by LastRide** [Shardj/zf1-future#50]
In composer.json we see that lib requires php >= 5.4 version.

```
    "require": {
        "php": ">=5.4"
    },
```

But in code I see some features that requires at least PHP 7.1 version:

```
[$type, $value] = [key($xml), current($xml)];
```

1. https://github.com/Shardj/zf1-future/blob/master/library/Zend/XmlRpc/Value.php#L489
2. https://github.com/Shardj/zf1-future/blob/master/library/Zend/XmlRpc/Value.php#L495

Let's either rewrite code to be compatible with PHP 5.4 or set minimal required version to PHP 7.1

**Comment by Shardj** [comment]
Thanks, good spot there

**Comment by Jimbolino** [comment]
@Shardj would you accept pull requests to make it compatible with older versions? My project currently runs at php 7.0, 7.2 and 7.4 / ubuntu 16,18,20 LTS

**Comment by Shardj** [comment]
Okay @Jimbolino go for it
