### ISSUE TITLE
Source for Zend_Config XML namespace?

### ISSUE THREAD

**Issue by C-Duv** [Shardj/zf1-future#57]
The `Zend_Config` has it's own XML namespace, which was available at http://framework.zend.com/xml/zend-config-xml/1.0/ (source: [`Zend_Config_Xml` Zend Framework Documentation](https://framework.zend.com/manual/1.12/en/zend.config.adapters.xml.html)).

But this XML resource is not available anymore.

And sadly I can't get a copy of it using [Wayback Machine](http://web.archive.org) because they had a special webpage served (when query was not coming from ZF?): https://github.com/zendframework/zf-web/blob/master/module/PageController/view/page-controller/zend-config-xml-1-0.phtml

Is there:
1. A copy of this XML somewhere (can't find it on GitHub)?
2. A place for this XML in the zf1-future repo?

**Comment by Shardj** [comment]
Unfortunately I don't know anything about this. I'll leave the issue here in case someone else see's this and can help you.

**Comment by C-Duv** [comment]
I asked Zend Framework Development team on Twitter: https://twitter.com/C_Duv/status/1243124536335351808

In the end, it looks like it's not a bug: I am not really sure there was a really a document at `http://framework.zend.com/xml/zend-config-xml/1.0/`, what's important is the URL, acting as a namespaceURI, not the document located at the URL.

I am closing this issue.
