### ISSUE TITLE
Update Zend_Version::getLatest()

### ISSUE THREAD

**Issue by joefresco** [Shardj/zf1-future#58]
Zend_Version::getLatest() currently accesses http://framework.zend.com/api/zf-version for the latest ZF1 version.

However, zf1-future has forked the repo and so this is broken.  getLatest() is currently reporting v 1.12.0 while zf1-future is presently at 1.17.0

**Comment by Shardj** [comment]
Thanks, good spot

**Comment by Shardj** [comment]
@joefresco got any ideas for a solution? I had a look at the packagist api and couldn't see anything to solve the issue

**Comment by joefresco** [comment]
A couple possible approaches

- Add a text file at the root of the framework (or somewhere else benign) that just contains the version #.  The latestVersion() check could then look up that text file in master on github.
- Look up github 'releases' if releases were all named identically and release #s were always the version #.  Docs:  https://developer.github.com/v3/repos/releases/#get-the-latest-release   (name or tag_name would probably be used -- the current name scheme would require splitting the name on the dash and NEVER using the dash as part of the version #.
   Example:  https://api.github.com/repos/Shardj/zf1-future/releases/latest
- Run a copy of zf1-future/master somewhere that auto-updates with any change to that branch.  I think an 'API' URL could be constructed that would report the version #.

**Comment by Shardj** [comment]
I seem to be getting 403 forbidden response codes back from `file_get_contents('https://api.github.com/repos/Shardj/zf1-future/releases/latest')` however accessing the url through my browser is no issue at all.

**Comment by joefresco** [comment]
Several options:  https://stackoverflow.com/questions/37141315/file-get-contents-gets-403-from-api-github-com-every-time

**Comment by Shardj** [comment]
Should be working now in release-1.17.1

**Comment by joefresco** [comment]
Thanks!
