### ISSUE TITLE
PHP 7.4 preloading compatibility

### ISSUE THREAD

**Issue by khonkisz** [Shardj/zf1-future#59]
When I try preload zend vendor it hangs. I excluded some clases and this works. But only on dev env it looks that it varies by enviroment, probably load order. 
Same php config, on docker I excluded:
'Zend_Soap_Client',
'Zend_Soap_AutoDiscover_Exception',
'Zend_EventManager_SharedEventManager',
'Zend_Feed_Writer',
'Zend_Feed',
And it works but when I move to production env it crash on diferent Classes.

**Comment by Shardj** [comment]
Sorry that this has been sitting here. I'm not sure what to do about your issue

**Comment by khonkisz** [comment]
It will be nice to have some preload script that returns correct classmap(not every class but mostly used by zend).

Symfony have this, https://symfony.com/blog/new-in-symfony-5-1-configurable-php-preloading and performance increase is huge 

> We've already implemented all these features in Symfony code. The result is that in our synthetic benchmarks, a sample application went from 360 requests per second to 630 requests per second, a 75% performance improvement.

**Comment by Shardj** [comment]
I don't really add features to zf1 normally, also this is a php 7.4 only feature which is quite restrictive as many users are still on 7.1 - 7.3

You can always add some preloading yourself to your app loader file to solve this without any changes in the zf1-future codebase.

**Comment by Shardj** [comment]
Are you using Zend_Loader_Autoloader at the moment? This is how we do it in our app loader file.

```
$loader = Zend_Loader_Autoloader::getInstance();
$loader->suppressNotFoundWarnings(true);
$loader->pushAutoloader(new \Pi\Core\Bootstrap\Autoloader(), ['Dashboard_', 'Xx']);
```

**Comment by Shardj** [comment]
I'm going to close this due to it's incompatibility with pre 7.4 versions for now. If you get back to me I can re-open this issue
