### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by viksts** [Shardj/zf1-future#60]
Hi,
My php version is 7.4.4 and phpunit version is 9.1.0 when i run my test-sut it gives error
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
vendor/shardj/zf1-future/library/Zend/Session.php:205
vendor/shardj/zf1-future/library/Zend/Session.php:445
No idea how to resolve this.

**Comment by Shardj** [comment]
Hi, what exactly are you doing?

According to the below linked SO post this means that you've already started sending content back so the headers can't be changed. This isn't something I've ever encountered with the zf1 framework.

https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

**Comment by Shardj** [comment]
I'll re-open the issue once you come back with some more information

**Comment by ikari-pl** [comment]
I am running into a similar issue, don't know why yet (trying to do a collosal 10-years-forward leap of what the code runs on)

```
IndexController
 ✘ Initialize [6.55 ms]
   │
   │ ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
   │
   │  vendor/shardj/zf1-future/library/Zend/Session.php:226
   │  vendor/shardj/zf1-future/library/Zend/Application/Resource/Session.php:112
   │  vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php:695
   │  vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php:638
   │  vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php:598
   │  vendor/shardj/zf1-future/library/Zend/Application.php:373
   │  vendor/shardj/zf1-future/library/Zend/Test/PHPUnit/ControllerTestCase.php:142
   │  vendor/shardj/zf1-future/library/Zend/Test/PHPUnit/ControllerTestCase.php:125
   │
```

wonder if the stack is of any help?
