### ISSUE TITLE
Cannot declare class Zend_Loader

### ISSUE THREAD

**Issue by MarceloLuis1997** [Shardj/zf1-future#65]
Hello!

I'm trying to install your package in an existing Zend Project but after running `composer require shardj/zf1-future` I'm getting this error:

`Fatal error: Cannot declare class Zend_Loader, because the name is already in use in C:\xampp\htdocs\docs\trunk\library\Zend\Loader.php on line 30`

Is there any additional configuration that's needed to do in the project?

Thank you very much!

**Comment by Naktibalda** [comment]
Delete `C:\xampp\htdocs\docs\trunk\library\Zend` directory.

**Comment by MarceloLuis1997** [comment]
> Delete `C:\xampp\htdocs\docs\trunk\library\Zend` directory.

*FACEPALM MOMENT* haha
It worked! Thank you very much @Naktibalda !
