### ISSUE TITLE
Zend_Validate_Hostname and new TLD

### ISSUE THREAD

**Issue by borissov** [Shardj/zf1-future#68]
Hello,
Hostname validator not support a lot of top level domains. In my opinion is so confusing and overloaded. This validator is used also in email validator. I think simpler validator may be is better.
What is your opinion?

P.S. Sorry for my bad English.

**Comment by Shardj** [comment]
I agree it's quite bad, personally I use jeremykendall's php-domain-parser https://github.com/jeremykendall/php-domain-parser to do all of this. I highly recommend you change over to using that or similar instead.

However, this repo isn't here to try and give zf1 new life. It's just to support those who are stuck on this framework, adding new features or changing things is pointless as people should be trying to leave this repo not stay on it. You're far better off using other libraries to fill in holes where zf1's existing functionality is lacking.

**Comment by Shardj** [comment]
Seems this guy has made a PR with what you need https://github.com/Shardj/zf1-future/pull/72
