### ISSUE TITLE
Is this comptiable with PHP 7.4 and 7.5 ?

### ISSUE THREAD

**Issue by vijaygarg-ahead** [Shardj/zf1-future#70]
Hello Shardj,

Have you checked Zend F1 version with PHP 7.4 and 7.5 version ?

**Comment by IMSoP** [comment]
Just FYI, there is no PHP 7.5, and probably never will be. The latest released version is 7.4, and the next planned version is 8.0.

Also, if you [search for 7.4 in this issue tracker](https://github.com/Shardj/zf1-future/issues?q=7.4) you will see various related issues, all marked resolved, apart from #59 which is a feature request from someone already running under 7.4.

**Comment by vijaygarg-ahead** [comment]
Thank you for reply. It means after 7.4, php 8 will be release.
