### ISSUE TITLE
Can not upload image in ap-south-1 - Asia Pacific (Mumbai) Region using ZF 1

### ISSUE THREAD

**Issue by vijaygarg-ahead** [Shardj/zf1-future#74]
Hello,

I have used "Asia Pacific (Mumbai)" region for uploading images but there are error is coming:

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message></Error>
0

Can anyone help me?

File Path: https://github.com/Shardj/zf1-future/blob/master/library/Zend/Service/Amazon/S3.php
Approx line: 784

**Comment by vijaygarg-ahead** [comment]
@Shardj  Can you check this issue ? 

Can any one help for this issue ?

**Comment by Pooky** [comment]
Hi, 

can you post full code which you using there? Also the whole stack trace would help.

**Comment by Shardj** [comment]
As I always say with these kinds of things, you really need to push through and convert to using AWS's SDK https://aws.amazon.com/sdk-for-php/ . From the sounds of it you're only just starting to implement this. If you really don't want to then I'd recommend you have a look at the authentication method AWS mentioned in your error message and compare it to the one Zend is using and see what's different. If you want to try and implement a new authentication method feel free as long as it doesn't cause any backwards compatibility breaks for anyone else.

**Comment by davejennings** [comment]
We came across this long before moving to this fork when moving our production environment over from eu-west-1 to eu-west-2.

As Shardj has mentioned, you'd be better off replacing your usage of `Zend_Service_Amazon_S3` with the AWS provided SDK. For us, that was as simple as pulling in that library with composer and replacing our bootstrapping of the stream wrapper e.g.

Replacing:

```
$s3 = new Zend_Service_Amazon_S3($key, $secret);
$s3->registerStreamWrapper("s3");
```

With:

```
$s3Client = new Aws\S3\S3Client([
    'region' => 'eu-west-2',
    'version' => 'latest',
    'credentials' => [
        'key' => $key,
        'secret' => $secret
    ]
]);
$s3Client->registerStreamWrapper();
```

**Comment by Shardj** [comment]
Thanks for the advice Dave, I hope that this helps you @vijaygarg-ahead. I'll close this as I won't be taking any action here

**Comment by vijaygarg-ahead** [comment]
> Thanks for the advice Dave, I hope that this helps you @vijaygarg-ahead. I'll close this as I won't be taking any action here

I will check the above solutions and update here.

**Comment by vijaygarg-ahead** [comment]
> We came across this long before moving to this fork when moving our production environment over from eu-west-1 to eu-west-2.
> 
> As Shardj has mentioned, you'd be better off replacing your usage of `Zend_Service_Amazon_S3` with the AWS provided SDK. For us, that was as simple as pulling in that library with composer and replacing our bootstrapping of the stream wrapper e.g.
> 
> Replacing:
> 
> ```
> $s3 = new Zend_Service_Amazon_S3($key, $secret);
> $s3->registerStreamWrapper("s3");
> ```
> 
> With:
> 
> ```
> $s3Client = new Aws\S3\S3Client([
>     'region' => 'eu-west-2',
>     'version' => 'latest',
>     'credentials' => [
>         'key' => $key,
>         'secret' => $secret
>     ]
> ]);
> $s3Client->registerStreamWrapper();
> ```

This solution is not working for me.

@Shardj  Please can you check the above file I have mentioned and let me know the solution.

**Comment by Shardj** [comment]
Hey @vijaygarg-ahead if you're having issues using the AWS SDK you should be able to find advice pretty much everywhere on the web since it's a very popular library. It's hard to provide a solution when I know nothing about the issue you're facing though.
