### ISSUE TITLE
Zend_Db_Select - Implement MySQL forced index statements

### ISSUE THREAD

**Issue by tsmgeek** [Shardj/zf1-future#77]
Is there any possibility to implement this patch?
Its MySQL specific so not sure the best way to implement this but thinking just to check the adaptor being used. It will work with mysqli and PDO::MySQL

https://github.com/zendframework/zf1/pull/509

**Comment by Jimbolino** [comment]
I think this is still valid: https://github.com/zendframework/zf1/pull/594#issuecomment-207347335

Just create a new class that extends the current one :)

**Comment by Shardj** [comment]
There seems to be a working solution for you in 594. I won't be merging either of those PR's for the same reason they weren't merged originally
