### ISSUE TITLE
Warning in PHP 7.3 using 'continue' in switch statement

### ISSUE THREAD

**Issue by gallien** [Shardj/zf1-future#8]
see https://github.com/Shardj/zf1-future/blob/2ad936d718824f0bcc4c8a46f486fbb759ff7d82/library/Zend/Pdf/FileParser/Font/OpenType.php#L901 and following lines

'continue' in switch statements are deprecated:
https://wiki.php.net/rfc/continue_on_switch_deprecation

I think, 'continue' should be changed to 'break' in all case statements in this method. 

In PHP 7.3 it shows warnings like 
**Warning**:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in ...

**Comment by Shardj** [comment]
Thanks, I'll get that sorted

**Comment by Shardj** [comment]
Looking at the debug log it seems to me that it should be continue 2 as it's trying to skip the $cmapType = $format; on line 934

**Comment by Shardj** [comment]
Fixed by commit: 4c7092339c249d83994212535d3a1427b736be64
