### ISSUE TITLE
Bootstrap error: Unable to resolve plugin "useragent"; no corresponding plugin with that name

### ISSUE THREAD

**Issue by kstenschke** [Shardj/zf1-future#92]
Bootstrap fails with error `Unable to resolve plugin "useragent"; no corresponding plugin with that name`
this error occurs on our system with zf1-future versions > 1.17.2

I suspect https://github.com/Shardj/zf1-future/commit/d822ef15e4c27f116c5bc25a2967c25b9ecac59c being related to the issue (added a comment into that commit as well).

Probably additional change of the autoloader configuration must be done after this diff, related info within readme.md would be helpful.

**Comment by Jimbolino** [comment]
do you have example code, how i can trigger this error?

**Comment by Drivez** [comment]
`$zf = new \Zend_Application(
				APP_ENV,
				APPLICATION_PATH . '/config/application.ini'
			);`

in the application.ini we had this option: 

`resources.useragent.mobile.features.classname = "Zend_Http_UserAgent_Features_Adapter_Browscap"`

after commenting this out, the application got bootstrapped and worked

**Comment by Drivez** [comment]
in the `vendor/shardj/zf1-future/library/Zend/Application/Resource/UserAgent.php` the class name is `UserAgent`, should it be `Zend_Application_Resource_UserAgent`? 

The rename of the class name worked for me.

**Comment by Jimbolino** [comment]
yes, as you were typing i also found the offending commits and reverted them in dev-master :)

**Comment by Drivez** [comment]
nice, a version bump so we can do a composer update?

**Comment by Jimbolino** [comment]
https://github.com/Shardj/zf1-future/releases/tag/release-1.18.5

**Comment by kstenschke** [comment]
In our installation, this problem was caused by a WURFL API configuration nestd in application.yaml (application.ini), under resources.useragent.wurflapi.

Configuration entry was: resources.useragent

The problem resolved by changing the entry into: resources.Zend_Application_Resource_UserAgent

**Comment by adli** [comment]
The problem still exists on Linux environment (case-sensitive filenames).

Please rename the file UserAgent.php to Useragent.php in /shardj/zf1-future/library/Zend/Application/Resource/ directory.

Thanks
