### ISSUE TITLE
Minimum PHP Version?

### ISSUE THREAD

**Issue by carsale24-avonarb** [Shardj/zf1-future#94]
What is minimum PHP Version for release 1.18.3 ? (Great project btw!)

**Comment by Shardj** [comment]
It's currently 7.0 due to some new syntax being introduced (https://github.com/Shardj/zf1-future/pull/90) however I believe @Jimbolino wanted to bring it back down to 5.6 syntax and was going to make a PR at some point

**Comment by Shardj** [comment]
I'm going to close this as the question is answered
