### ISSUE TITLE
Merge with zf1s

### ISSUE THREAD

**Issue by glensc** [Shardj/zf1-future#96]
Merge efforts with zf1s project:
- https://github.com/zf1s/zf1

it's code lives in monorepo:
- https://github.com/zf1s/zf1

but also code is split to sub-packages to benefit composer install of needed components only.

x-ref:
- https://github.com/zf1s/zf1/issues/25

**Comment by Shardj** [comment]
I don't plan on doing some large merge at any point. If there are any important changes on zf1s that you feel are missing from this repo though please feel free to make a pull request

**Comment by glensc** [comment]
Port needed to this repo:
- https://github.com/zf1s/zf1/pull/26#issuecomment-700843265

**Comment by glensc** [comment]
Port needed to this repo:
- https://github.com/zf1s/zf1/pull/27#issuecomment-702554375

**Comment by Shardj** [comment]
@glensc you know what you're doing so I've invited you as a contributor

**Comment by glensc** [comment]
@Shardj thanks, but I'm only interested in improving zf1s side due to its package split and composer support and retaining support for legacy PHP versions and only providing continued support, not change/improve things.

However,
I'll keep providing two-way feedback on issues arising in zf1s project unless you tell me to stop.

Aside, would be nice to have opposite tracking too, or I'll just subscribe to this project updates.

**Comment by glensc** [comment]
You can cherry-pick the commits from zf1s with something like this:

1. go to PR page: https://github.com/zf1s/zf1/pull/39
2. append .patch to the URL: https://github.com/zf1s/zf1/pull/39.patch
2. download that locally: `wget https://github.com/zf1s/zf1/pull/39.patch`
2. apply with git am: `git am 39.patch`
3. git push, git, branch, etc

**Comment by Shardj** [comment]
@glensc thanks that's very helpful

**Comment by Shardj** [comment]
Doesn't seem to be working for me as the patch always fails, even after I fix the file paths. I'll just manually do this

**Comment by Shardj** [comment]
Ah it seems that for that particular patch we already fixed this code a while back

**Comment by glensc** [comment]
ah, `git am` may not work if the project file layout is totally different. but you can use `git commit --author 'XXX xxx@example.com' --date 'some timestamp'` to preserve author and commit date.

**Comment by glensc** [comment]
cherry-picking zf1s -> zf1-future is much easier when adding zf1s as remove, git is able to understand path renames.

example:
```
git remote add zf1s ../zf1s
git cherry-pick 232e616b8a3b4d278151f4d12214d3f5c43cc31b
```

later can manually compare both diffs:

```
git show 232e616b8a3b4d278151f4d12214d3f5c43cc31b > 1.patch
git show > 2.patch
diff 1.patch 2.patch
```

**Comment by glensc** [comment]
Carried 2022:
- https://github.com/Shardj/zf1-future/pull/265
