### ISSUE TITLE
Zend_Mail & TLS1.2 - Unable to connect via TLS

### ISSUE THREAD

**Issue by gavinsbtm** [Shardj/zf1-future#99]
I know this isn't an issue with zf1-future exactly but thought I might get some help here.

I have an old app running on an old server that connects to my a mail server that has just dropped support for TLS1.0 and TLS1.1 - TLS1.2 must now be used.

I can connect and send an email via the terminal so I don't think there is a problem with TLS1.2 not being supported on my server, however in php if I dump stream_get_transports() I get:

I've seen a workaround where Zend_Mail_Protocol_Smtp can be modified by changing a line in the helo function to:
    if (true !== $enableCrypto = stream_socket_enable_crypto($this->_socket, true, STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT))
but this will only work on php>=5.6.

[0] => string(3) "tcp"
[1] => string(3) "udp"
[2] => string(4) "unix"
[3] => string(3) "udg"
[4] => string(3) "ssl"
[5] => string(5) "sslv3"
[6] => string(3) "tls"

How can I make Zend_Mail use TLS1.2?

My server setup:
Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9
OpenSSL 1.0.1f

Thanks for any feed back.

**Comment by Shardj** [comment]
Hey, this is a bit outside of my area of expertise, however I'll leave this here so others may be able to lend a hand. And if you ever figure out a nice solution feel free to make a pull request.

**Comment by gavinsbtm** [comment]
I've not been able to find an easy solution to this. Bottom line is the php version is too old.
I have set up a new virtual machine as a web server with php5.6 and php7.4 - slowly going to start porting the apps over.

Now I have php5.6 available - I have been able to implement this workaround https://discourse.laminas.dev/t/zf-1-12-18-tls-error/1479.

It basically extends Zend_Mail_Protocol_Smtp and modifies the helo() function to use STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT. You then create a connection using the modified helo function and pass the new connection to the mail transport.

Could be worth defaulting to TLSv1.2 as many hosts are dropping support for older methods but that would mean a minimum requirement of php5.6.

**Comment by Jimbolino** [comment]
This is a complicated issue, because PHP has been very inconsistent with the STREAM_CRYPTO_METHOD_TLS_CLIENT constant:

https://3v4l.org/Tg2QI

basically between 5.6.7 and 7.2.0 it was broken to only support TLS1.0
https://github.com/php/php-src/commit/10bc5fd4c4c8e1dd57bd911b086e9872a56300a0#diff-714485dc5d2ba8617ba0cb2dbfb7cd36R178

So make sure you are using 7.2 or newer

**Comment by Shardj** [comment]
I'm going to close this as it has been a month without any action, feel free to re-open the issue if you're still having trouble @gavinsbtm

**Comment by francescozanoni** [comment]
Hi, just submitted a [pull request](https://github.com/Shardj/zf1-future/pull/122) for this, by adding these two confoguration parameters:
```
resources.mail.transport.verify_peer = false
resources.mail.transport.verify_peer_name = false
```

Hope it helps.
